var PageJs=new Class.create;
PageJs.prototype=Object.extend(new BPCPageJs,{id_wrapper:"",_acceptableTypes:["csv"],csvFileLineFormat:[],_fileReader:null,_uploadedData:{},_importDataTypes:{},_rowNo:null,_selectTypeTxt:"Select a Import Type",load:function(a){this._rowNo=1;this._importDataTypes=a;$(this.getHTMLID("importerDiv")).update("test");window.File&&window.FileReader&&window.FileList&&window.Blob?(this._fileReader=new FileReader,$(this.getHTMLID("importerDiv")).update(this._getFileUploadDiv()),this._loadChosen()):$(this.getHTMLID("importerDiv")).update(this.getAlertBox("Warning:",
"Your browser does NOT support this feature. pls change and try again").addClassName("alert-warning"));return this},_genTemplate:function(){var a,b;if(this.type=this._getUploadType())a=[],a.push(this.csvFileLineFormat.join(", ")+"\n"),b=new Date,b=this.type+"_"+b.getFullYear()+"_"+b.getMonth()+"_"+b.getDate()+"_"+b.getHours()+"_"+b.getMinutes()+"_"+b.getSeconds()+".csv",a=new Blob(a,{type:"text/csv;charset=utf-8"}),saveAs(a,b);return this},_loadChosen:function(){jQuery(".chosen").chosen({search_contains:!0,
inherit_select_classes:!0,no_results_text:"No code type found!",width:"250px"});return this},_getFileUploadDiv:function(){var a,b,d,c;a=this;b=(new Element("div",{"class":"panel panel-default drop_file_div",title:"You can drag multiple files here!"})).insert({bottom:(new Element("div",{"class":"panel-body"})).insert({bottom:(new Element("div",{"class":"pull-right"})).insert({bottom:d=(new Element("select",{"class":"chosen","data-placeholder":"Code Type: ",id:a.getHTMLID("importDataTypesDropdownId")})).insert({bottom:(new Element("option",
{value:a._selectTypeTxt})).update(a._selectTypeTxt)})}).insert({bottom:(new Element("span",{"class":"btn btn-default btn-xs",title:"Download Template"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-download-alt"})}).observe("click",function(){a._genTemplate()})})}).insert({bottom:(new Element("div",{"class":"form-group center-block text-left",style:"width: 50%"})).insert({bottom:(new Element("label")).update("Drop you files here or select your file below:")}).insert({bottom:c=
(new Element("input",{type:"file",style:"display: none;"})).observe("change",function(b){a._readFiles(b.target.files)})}).insert({bottom:new Element("div",{"class":"clearfix"})}).insert({bottom:(new Element("span",{"class":"btn btn-success clearfix"})).update("Click to select your file").observe("click",function(b){a._getUploadType()&&c.click()})}).insert({bottom:new Element("div",{"class":"clearfix"})}).insert({bottom:(new Element("small")).update("ONLY ACCEPT file formats: "+a._acceptableTypes.join(", "))})})}).observe("dragover",
function(a){a.stopPropagation();a.preventDefault();a.dataTransfer.dropEffect="copy"}).observe("drop",function(b){a._getUploadType()&&(b.stopPropagation(),b.preventDefault(),a._readFiles(b.dataTransfer.files))});$H(a._importDataTypes).each(function(a){d.insert({bottom:(new Element("option",{value:a.key})).store("data",a.key).update(a.value)})});return b},_getUploadType:function(){this.dropdown=$(this.getHTMLID("importDataTypesDropdownId"));this._importDataTypes=$F(this.dropdown);if(this._importDataTypes===
this._selectTypeTxt)return this.showModalBox("Please select a import type first","Invalid inport type"),!1;switch(this._importDataTypes){case "myob_ean":case "myob_upc":this.csvFileLineFormat=["sku","itemNo"];break;case "stockAdjustment":this.csvFileLineFormat="sku stockOnPO stockOnHand stockOnOrder stockInRMA stockInParts totalInPartsValue totalOnHandValue active comment".split(" ");break;case "accounting":this.csvFileLineFormat=["sku","assetAccNo","costAccNo","revenueAccNo"];break;case "accountingCode":this.csvFileLineFormat=
["description","code"];break;default:this.csvFileLineFormat=[]}return this._importDataTypes},_readFiles:function(a){var b,d,c,e,f,g,k,h,m,l;b=this;b._uploadedData={};d=new Element("div",{"class":"list-group"});for(c=0;c<a.length();c++)e=a[c],f=(new Element("div",{"class":"row"})).update((new Element("div",{"class":"col-lg-6 col-md-6"})).update(e.name)),""!==(g=e.name.split(".").pop())&&-1<b._acceptableTypes.indexOf(g.toLowerCase())?(b._fileReader=new FileReader,b._fileReader.onload=function(a){b._rowNo=
1;a.target.result.split(/\r\n|\n|\r/).each(function(a){if(null!==a&&!a.blank()&&(k=[],a.split(",").each(function(a){null!==a&&k.push(a.strip())}),h=k.join(","),h!==b.csvFileLineFormat.join(","))){m={};for(l=0;l<b.csvFileLineFormat.size();l++)m[b.csvFileLineFormat[l]]=k[l];m.index=b._rowNo++;b._uploadedData[h]=m}})},b._fileReader.readAsText(e),e=!0):(f.insert({bottom:(new Element("div",{"class":"col-lg-6 col-md-6"})).update((new Element("small")).update("Not supported file extension: "+g))}),e=!1),
d.insert({bottom:(new Element("div",{"class":"list-group-item "+(!0===e?"list-group-item-success":"list-group-item-danger")})).insert({bottom:f})});$(b.getHTMLID("importerDiv")).update((new Element("div",{"class":"panel panel-default"})).insert({bottom:(new Element("div",{"class":"panel-heading"})).update("Files Selected:").insert({bottom:(new Element("small",{"class":"pull-right"})).update("ONLY ACCEPT file formats: "+b._acceptableTypes.join(", "))})}).insert({bottom:d}).insert({bottom:(new Element("div",
{"class":"panel-footer"})).insert({bottom:(new Element("span",{"class":"btn btn-success"})).update("Start").observe("click",function(){b._loadProductLineItems()})}).insert({bottom:(new Element("span",{"class":"btn btn-warning pull-right"})).update("Cancel").observe("click",function(){jQuery(".btn").attr("disabled","disabled");window.location=document.URL})})}));return b},genCSV:function(a){var b,d,c,e;b=[];d=$(a).up(".panel").getElementsBySelector(".result_row.result-done");if(!(1>d.length))return c=
"",$H(d[0].retrieve("data")).each(function(a){c=c+a.key+", "}),b.push(c+"\n"),$(a).up(".panel").getElementsBySelector(".result_row.result-done").each(function(a){e="";$H(a.retrieve("data")).each(function(a){e=e+a.value+", "});e+="\n";b.push(e)}),a=new Date,a=this._importDataTypes+"_match_"+a.getFullYear()+"_"+a.getMonth()+"_"+a.getDate()+"_"+a.getHours()+"_"+a.getMinutes()+"_"+a.getSeconds()+".csv",d=new Blob(b,{type:"text/csv;charset=utf-8"}),saveAs(d,a),this},_openDetailPage:function(a,b){window.open("/"+
a+"/"+b+".html",a+" details","width=1300, location=no, scrollbars=yes, menubar=no, status=no, titlebar=no, fullscreen=no, toolbar=no").focus();return this},_getProductLineItem:function(a,b,d){var c,e,f,g,k,h;c=this;e=c._uploadedData[d[b]];f=new Element("tr",{"class":"result_row info"});c.csvFileLineFormat.each(function(a){$H(e).each(function(b){b.key===a&&f.insert({bottom:(new Element("th",{style:b.value?"":"color:red;"})).update(b.value?b.value:"Blank "+a)})})});e.importDataTypes=c._importDataTypes;
c.postAjax(c.getCallbackId("getAllCodeForProduct"),e,{onCreate:function(b,c){a.insert({bottom:f})},onSuccess:function(b,d){try{g=c.getResp(d,!1,!0),g.item.id?(f.removeClassName("info").addClassName("result-done").store("data",g.item).down("th"),g.path&&f.down("th").setStyle({cursor:"pointer","text-decoration":"underline"}).observe("click",function(){c._openDetailPage(g.path,g.item.id)})):f.update("")}catch(h){f.removeClassName("info").addClassName("danger").store("data",e).insert({bottom:(new Element("td",
{colspan:2})).update("<strong>ERROR:</strong>"+h)}),a.insert({top:f})}},onComplete:function(e,f){try{k=1*b+1,k>=d.size()?(h=$(c.getHTMLID("importerDiv")).getElementsBySelector(".result_row.danger"),a.up(".panel").removeClassName("panel-danger").addClassName(0<h.size()?"panel-warning":"panel-success").down(".panel-heading").update("").insert({bottom:(new Element("panel-title")).update(0<h.size()?"All provided rows have been proccessed, but with "+h.size()+" error(s)":"All provided rows have been proccessed successfully")}).insert({bottom:(new Element("span",
{"class":"btn-group btn-group-sm pull-right"})).insert({bottom:(new Element("span",{"class":"btn hidden"})).writeAttribute("title",0<h.size()?"Export Success Rows":"Export To Excel").update(new Element("span",{"class":"glyphicon glyphicon-save"})).addClassName(0<h.size()?"btn-warning":"btn-success").observe("click",function(){c.genCSV(this)})}).insert({bottom:(new Element("span",{"class":"btn btn-default"})).writeAttribute("title","Start Again").update(new Element("span",{"class":"glyphicon glyphicon-repeat"})).observe("click",
function(){window.location=document.URL})})})):c._getProductLineItem(a,k,d)}catch(g){alert(g)}}});return c},_loadProductLineItems:function(){var a,b,d;a=[];$H(this._uploadedData).each(function(b){a.push(b.key)});b=new Element("tr");this.csvFileLineFormat.each(function(a){b.insert({bottom:(new Element("th")).update(a)})});$(this.getHTMLID("importerDiv")).update((new Element("div",{"class":"price_search_result panel panel-danger table-responsive"})).insert({bottom:(new Element("div",{"class":"panel-heading"})).update("Total of <strong>"+
a.size()+"</strong> unique row(s) received:").insert({bottom:(new Element("strong",{"class":"pull-right"})).update("please waiting for it to finish")})}).insert({bottom:(new Element("table",{"class":"table table-striped"})).insert({bottom:(new Element("thead")).update(b)}).insert({bottom:d=new Element("tbody")})}));this._getProductLineItem(d,0,a);return this}});