var PageJs=new Class.create
PageJs.prototype=Object.extend(new BPCPageJs,{id_wrapper:"",_acceptableTypes:["csv"],csvFileLineFormat:[],_fileReader:null,_uploadedData:{},_htmlIds:{},_importDataTypes:{},_rowNo:null,_selectTypeTxt:"Select a Import Type",setHTMLIDs:function(e,t){var n={}
return n.me=this,n.me._htmlIds.importerDiv=e,n.me._htmlIds.importDataTypesDropdown=t,n.me.id_wrapper=n.me._htmlIds.importerDiv,this},load:function(e){var t={}
return t.me=this,t.me._rowNo=1,t.me._importDataTypes=e,$(t.me._htmlIds.importerDiv).update("test"),window.File&&window.FileReader&&window.FileList&&window.Blob?(t.me._fileReader=new FileReader,$(t.me._htmlIds.importerDiv).update(t.me._getFileUploadDiv()),t.me._loadChosen()):$(t.me.id_wrapper).update(t.me.getAlertBox("Warning:","Your browser does NOT support this feature. pls change and try again").addClassName("alert-warning")),t.me},_genTemplate:function(){var e={}
return e.me=this,(e.me.type=e.me._getUploadType())&&(e.data=[],e.data.push(e.me.csvFileLineFormat.join(", ")+"\n"),e.now=new Date,e.fileName=e.me.type+"_"+e.now.getFullYear()+"_"+e.now.getMonth()+"_"+e.now.getDate()+"_"+e.now.getHours()+"_"+e.now.getMinutes()+"_"+e.now.getSeconds()+".csv",e.blob=new Blob(e.data,{type:"text/csv;charset=utf-8"}),saveAs(e.blob,e.fileName)),e.me},_loadChosen:function(){return jQuery(".chosen").chosen({search_contains:!0,inherit_select_classes:!0,no_results_text:"No code type found!",width:"250px"}),this},_getFileUploadDiv:function(){var e={}
return e.me=this,e.newDiv=new Element("div",{"class":"panel panel-default drop_file_div",title:"You can drag multiple files here!"}).insert({bottom:new Element("div",{"class":"panel-body"}).insert({bottom:new Element("div",{"class":"pull-right"}).insert({bottom:e.dropdown=new Element("select",{"class":"chosen","data-placeholder":"Code Type: ",id:e.me._htmlIds.importDataTypesDropdown}).insert({bottom:new Element("option",{value:e.me._selectTypeTxt}).update(e.me._selectTypeTxt)})}).insert({bottom:new Element("span",{"class":"btn btn-default btn-xs",title:"Download Template"}).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-download-alt"})}).observe("click",function(){e.me._genTemplate()})})}).insert({bottom:new Element("div",{"class":"form-group center-block text-left",style:"width: 50%"}).insert({bottom:new Element("label").update("Drop you files here or select your file below:")}).insert({bottom:e.inputFile=new Element("input",{type:"file",style:"display: none;"}).observe("change",function(t){e.me._readFiles(t.target.files)})}).insert({bottom:new Element("div",{"class":"clearfix"})}).insert({bottom:new Element("span",{"class":"btn btn-success clearfix"}).update("Click to select your file").observe("click",function(){e.me._getUploadType()&&e.inputFile.click()})}).insert({bottom:new Element("div",{"class":"clearfix"})}).insert({bottom:new Element("small").update("ONLY ACCEPT file formats: "+e.me._acceptableTypes.join(", "))})})}).observe("dragover",function(e){e.stopPropagation(),e.preventDefault(),e.dataTransfer.dropEffect="copy"}).observe("drop",function(t){e.me._getUploadType()&&(t.stopPropagation(),t.preventDefault(),e.me._readFiles(t.dataTransfer.files))}),$H(e.me._importDataTypes).each(function(t){e.dropdown.insert({bottom:new Element("option",{value:t.key}).store("data",t.key).update(t.value)})}),e.newDiv},_getUploadType:function(){var e={}
if(e.me=this,e.me.dropdown=$(e.me._htmlIds.importDataTypesDropdown),e.me._importDataTypes=$F(e.me.dropdown),e.me._importDataTypes===e.me._selectTypeTxt)return e.me.showModalBox("Please select a import type first","Invalid inport type"),!1
switch(e.me._importDataTypes){case"myob_ean":case"myob_upc":e.me.csvFileLineFormat=["sku","itemNo"]
break
case"stockAdjustment":e.me.csvFileLineFormat=["sku","stockOnPO","stockOnHand","stockOnOrder","stockInRMA","stockInParts","totalInPartsValue","totalOnHandValue","active","comment"]
break
case"accounting":e.me.csvFileLineFormat=["sku","assetAccNo","costAccNo","revenueAccNo"]
break
case"accountingCode":e.me.csvFileLineFormat=["description","code"]
break
default:e.me.csvFileLineFormat=[]}return e.me._importDataTypes},_readFiles:function(e){var t={}
for(t.me=this,t.me._uploadedData={},t.fileLists=new Element("div",{"class":"list-group"}),t.i=0,t.file;t.file=e[t.i];t.i++)t.fileRow=new Element("div",{"class":"row"}).update(new Element("div",{"class":"col-lg-6 col-md-6"}).update(t.file.name)),""!==(t.extension=t.file.name.split(".").pop())&&t.me._acceptableTypes.indexOf(t.extension.toLowerCase())>-1?(t.me._fileReader=new FileReader,t.me._fileReader.onload=function(e){t.me._rowNo=1,e.target.result.split(/\r\n|\n|\r/).each(function(e){if(null!==e&&!e.blank()&&(t.cols=[],e.split(",").each(function(e){null!==e&&t.cols.push(e.strip())}),t.key=t.cols.join(","),t.key!==t.me.csvFileLineFormat.join(","))){for(t.colArray={},t.j=0;t.j<t.me.csvFileLineFormat.size();t.j++)t.colArray[t.me.csvFileLineFormat[t.j]]=t.cols[t.j]
t.colArray.index=t.me._rowNo++,t.me._uploadedData[t.key]=t.colArray}})},t.me._fileReader.readAsText(t.file),t.supported=!0):(t.fileRow.insert({bottom:new Element("div",{"class":"col-lg-6 col-md-6"}).update(new Element("small").update("Not supported file extension: "+t.extension))}),t.supported=!1),t.fileLists.insert({bottom:new Element("div",{"class":"list-group-item "+(t.supported===!0?"list-group-item-success":"list-group-item-danger")}).insert({bottom:t.fileRow})})
return $(t.me.id_wrapper).update(new Element("div",{"class":"panel panel-default"}).insert({bottom:new Element("div",{"class":"panel-heading"}).update("Files Selected:").insert({bottom:new Element("small",{"class":"pull-right"}).update("ONLY ACCEPT file formats: "+t.me._acceptableTypes.join(", "))})}).insert({bottom:t.fileLists}).insert({bottom:new Element("div",{"class":"panel-footer"}).insert({bottom:new Element("span",{"class":"btn btn-success"}).update("Start").observe("click",function(){t.me._loadProductLineItems()})}).insert({bottom:new Element("span",{"class":"btn btn-warning pull-right"}).update("Cancel").observe("click",function(){jQuery(".btn").attr("disabled","disabled"),window.location=document.URL})})})),t.me},genCSV:function(e){var t={}
return t.me=this,t.data=[],t.originalDataRows=$(e).up(".panel").getElementsBySelector(".result_row.result-done"),t.originalDataRows.length<1?void 0:(t.headerRow="",$H(t.originalDataRows[0].retrieve("data")).each(function(e){t.headerRow=t.headerRow+e.key+", "}),t.data.push(t.headerRow+"\n"),$(e).up(".panel").getElementsBySelector(".result_row.result-done").each(function(e){t.csvRow="",$H(e.retrieve("data")).each(function(e){t.csvRow=t.csvRow+e.value+", "}),t.csvRow=t.csvRow+"\n",t.data.push(t.csvRow),t.i=1*t.i+1}),t.now=new Date,t.fileName=t.me._importDataTypes+"_match_"+t.now.getFullYear()+"_"+t.now.getMonth()+"_"+t.now.getDate()+"_"+t.now.getHours()+"_"+t.now.getMinutes()+"_"+t.now.getSeconds()+".csv",t.blob=new Blob(t.data,{type:"text/csv;charset=utf-8"}),saveAs(t.blob,t.fileName),t.me)},_openDetailPage:function(e,t){var n={}
return n.me=this,n.newWindow=window.open("/"+e+"/"+t+".html",e+" details","width=1300, location=no, scrollbars=yes, menubar=no, status=no, titlebar=no, fullscreen=no, toolbar=no"),n.newWindow.focus(),n.me},_getProductLineItem:function(e,t,n){var o={}
return o.me=this,o.data=o.me._uploadedData[n[t]],o.newRow=new Element("tr",{"class":"result_row info"}),o.me.csvFileLineFormat.each(function(e){$H(o.data).each(function(t){t.key===e&&o.newRow.insert({bottom:new Element("th",{style:t.value?"":"color:red;"}).update(t.value?t.value:"Blank "+e)})})}),o.data.importDataTypes=o.me._importDataTypes,o.me.postAjax(o.me.getCallbackId("getAllCodeForProduct"),o.data,{onLoading:function(){e.insert({bottom:o.newRow})},onSuccess:function(t,n){try{if(o.result=o.me.getResp(n,!1,!0),!o.result.item.id)return void o.newRow.update("")
o.newRow.removeClassName("info").addClassName("result-done").store("data",o.result.item).down("th"),o.result.path&&o.newRow.down("th").setStyle({cursor:"pointer","text-decoration":"underline"}).observe("click",function(){o.me._openDetailPage(o.result.path,o.result.item.id)})}catch(a){o.newRow.removeClassName("info").addClassName("danger").store("data",o.data).insert({bottom:new Element("td",{colspan:2}).update("<strong>ERROR:</strong>"+a)}),e.insert({top:o.newRow})}},onComplete:function(){try{o.nextDataKeyIndex=1*t+1,o.nextDataKeyIndex>=n.size()?(o.errRows=$(o.me.id_wrapper).getElementsBySelector(".result_row.danger"),e.up(".panel").removeClassName("panel-danger").addClassName(o.errRows.size()>0?"panel-warning":"panel-success").down(".panel-heading").update("").insert({bottom:new Element("panel-title").update(o.errRows.size()>0?"All provided rows have been proccessed, but with "+o.errRows.size()+" error(s)":"All provided rows have been proccessed successfully")}).insert({bottom:new Element("span",{"class":"btn-group btn-group-sm pull-right"}).insert({bottom:new Element("span",{"class":"btn hidden"}).writeAttribute("title",o.errRows.size()>0?"Export Success Rows":"Export To Excel").update(new Element("span",{"class":"glyphicon glyphicon-save"})).addClassName(o.errRows.size()>0?"btn-warning":"btn-success").observe("click",function(){o.me.genCSV(this)})}).insert({bottom:new Element("span",{"class":"btn btn-default"}).writeAttribute("title","Start Again").update(new Element("span",{"class":"glyphicon glyphicon-repeat"})).observe("click",function(){window.location=document.URL})})})):o.me._getProductLineItem(e,o.nextDataKeyIndex,n)}catch(a){alert(a)}}}),o.me},_loadProductLineItems:function(){var e={}
return e.me=this,e.keys=[],$H(e.me._uploadedData).each(function(t){e.keys.push(t.key)}),e.theadRow=new Element("tr"),e.me.csvFileLineFormat.each(function(t){e.theadRow.insert({bottom:new Element("th").update(t)})}),$(e.me.id_wrapper).update(new Element("div",{"class":"price_search_result panel panel-danger table-responsive"}).insert({bottom:new Element("div",{"class":"panel-heading"}).update("Total of <strong>"+e.keys.size()+"</strong> unique row(s) received:").insert({bottom:new Element("strong",{"class":"pull-right"}).update("please waiting for it to finish")})}).insert({bottom:new Element("table",{"class":"table table-striped"}).insert({bottom:new Element("thead").update(e.theadRow)}).insert({bottom:e.resultList=new Element("tbody")})})),e.me._getProductLineItem(e.resultList,0,e.keys),e.me}})