var PageJs=new Class.create;
PageJs.prototype=Object.extend(new BPCPageJs,{id_wrapper:"",_acceptableTypes:["csv"],csvFileLineFormat:[],_fileReader:null,_uploadedData:{},_importDataTypes:{},_rowNo:null,_selectTypeTxt:"Select a Import Type",load:function(b){this._rowNo=1;this._importDataTypes=b;$(this.getHTMLID("importerDiv")).update("test");window.File&&window.FileReader&&window.FileList&&window.Blob?(this._fileReader=new FileReader,$(this.getHTMLID("importerDiv")).update(this._getFileUploadDiv()),this._loadChosen()):$(this.getHTMLID("importerDiv")).update(this.getAlertBox("Warning:",
"Your browser does NOT support this feature. pls change and try again").addClassName("alert-warning"));return this},_genTemplate:function(){var b,a;if(this.type=this._getUploadType())b=[],b.push(this.csvFileLineFormat.join(", ")+"\n"),a=new Date,a=this.type+"_"+a.getFullYear()+"_"+a.getMonth()+"_"+a.getDate()+"_"+a.getHours()+"_"+a.getMinutes()+"_"+a.getSeconds()+".csv",b=new Blob(b,{type:"text/csv;charset=utf-8"}),saveAs(b,a);return this},_loadChosen:function(){jQuery(".chosen").chosen({search_contains:!0,
inherit_select_classes:!0,no_results_text:"No code type found!",width:"250px"});return this},_getFileUploadDiv:function(){var b,a,d,c;b=this;a=(new Element("div",{"class":"panel panel-default drop_file_div",title:"You can drag multiple files here!"})).insert({bottom:(new Element("div",{"class":"panel-body"})).insert({bottom:(new Element("div",{"class":"pull-right"})).insert({bottom:d=(new Element("select",{"class":"chosen","data-placeholder":"Code Type: ",id:b.getHTMLID("importDataTypesDropdownId")})).insert({bottom:(new Element("option",
{value:b._selectTypeTxt})).update(b._selectTypeTxt)})}).insert({bottom:(new Element("span",{"class":"btn btn-default btn-xs",title:"Download Template"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-download-alt"})}).observe("click",function(){b._genTemplate()})})}).insert({bottom:(new Element("div",{"class":"form-group center-block text-left",style:"width: 50%"})).insert({bottom:(new Element("label")).update("Drop you files here or select your file below:")}).insert({bottom:c=
(new Element("input",{type:"file",style:"display: none;"})).observe("change",function(a){b._readFiles(a.target.files)})}).insert({bottom:new Element("div",{"class":"clearfix"})}).insert({bottom:(new Element("span",{"class":"btn btn-success clearfix"})).update("Click to select your file").observe("click",function(a){b._getUploadType()&&c.click()})}).insert({bottom:new Element("div",{"class":"clearfix"})}).insert({bottom:(new Element("small")).update("ONLY ACCEPT file formats: "+b._acceptableTypes.join(", "))})})}).observe("dragover",
function(a){a.stopPropagation();a.preventDefault();a.dataTransfer.dropEffect="copy"}).observe("drop",function(a){b._getUploadType()&&(a.stopPropagation(),a.preventDefault(),b._readFiles(a.dataTransfer.files))});$H(b._importDataTypes).each(function(a){d.insert({bottom:(new Element("option",{value:a.key})).store("data",a.key).update(a.value)})});return a},_getUploadType:function(){this.dropdown=$(this.getHTMLID("importDataTypesDropdownId"));this._importDataTypes=$F(this.dropdown);if(this._importDataTypes===
this._selectTypeTxt)return this.showModalBox("Please select a import type first","Invalid inport type"),!1;switch(this._importDataTypes){case "myob_ean":case "myob_upc":this.csvFileLineFormat=["sku","itemNo"];break;case "stockAdjustment":this.csvFileLineFormat="sku stockOnPO stockOnHand stockOnOrder stockInRMA stockInParts totalInPartsValue totalOnHandValue active comment".split(" ");break;case "accounting":this.csvFileLineFormat=["sku","assetAccNo","costAccNo","revenueAccNo"];break;case "accountingCode":this.csvFileLineFormat=
["description","code"];break;default:this.csvFileLineFormat=[]}return this._importDataTypes},_readFiles:function(b){var a={me:this};a.me._uploadedData={};a.fileLists=new Element("div",{"class":"list-group"});a.i=0;for(a.file;a.file=b[a.i];a.i++)a.fileRow=(new Element("div",{"class":"row"})).update((new Element("div",{"class":"col-lg-6 col-md-6"})).update(a.file.name)),""!==(a.extension=a.file.name.split(".").pop())&&-1<a.me._acceptableTypes.indexOf(a.extension.toLowerCase())?(a.me._fileReader=new FileReader,
a.me._fileReader.onload=function(b){a.me._rowNo=1;b.target.result.split(/\r\n|\n|\r/).each(function(b){if(null!==b&&!b.blank()&&(a.cols=[],b.split(",").each(function(b){null!==b&&a.cols.push(b.strip())}),a.key=a.cols.join(","),a.key!==a.me.csvFileLineFormat.join(","))){a.colArray={};for(a.j=0;a.j<a.me.csvFileLineFormat.size();a.j++)a.colArray[a.me.csvFileLineFormat[a.j]]=a.cols[a.j];a.colArray.index=a.me._rowNo++;a.me._uploadedData[a.key]=a.colArray}})},a.me._fileReader.readAsText(a.file),a.supported=
!0):(a.fileRow.insert({bottom:(new Element("div",{"class":"col-lg-6 col-md-6"})).update((new Element("small")).update("Not supported file extension: "+a.extension))}),a.supported=!1),a.fileLists.insert({bottom:(new Element("div",{"class":"list-group-item "+(!0===a.supported?"list-group-item-success":"list-group-item-danger")})).insert({bottom:a.fileRow})});$(a.me.getHTMLID("importerDiv")).update((new Element("div",{"class":"panel panel-default"})).insert({bottom:(new Element("div",{"class":"panel-heading"})).update("Files Selected:").insert({bottom:(new Element("small",
{"class":"pull-right"})).update("ONLY ACCEPT file formats: "+a.me._acceptableTypes.join(", "))})}).insert({bottom:a.fileLists}).insert({bottom:(new Element("div",{"class":"panel-footer"})).insert({bottom:(new Element("span",{"class":"btn btn-success"})).update("Start").observe("click",function(){a.me._loadProductLineItems()})}).insert({bottom:(new Element("span",{"class":"btn btn-warning pull-right"})).update("Cancel").observe("click",function(){jQuery(".btn").attr("disabled","disabled");window.location=
document.URL})})}));return a.me},genCSV:function(b){var a,d,c,e;a=[];d=$(b).up(".panel").getElementsBySelector(".result_row.result-done");if(!(1>d.length))return c="",$H(d[0].retrieve("data")).each(function(a){c=c+a.key+", "}),a.push(c+"\n"),$(b).up(".panel").getElementsBySelector(".result_row.result-done").each(function(b){e="";$H(b.retrieve("data")).each(function(a){e=e+a.value+", "});e+="\n";a.push(e)}),b=new Date,b=this._importDataTypes+"_match_"+b.getFullYear()+"_"+b.getMonth()+"_"+b.getDate()+
"_"+b.getHours()+"_"+b.getMinutes()+"_"+b.getSeconds()+".csv",d=new Blob(a,{type:"text/csv;charset=utf-8"}),saveAs(d,b),this},_openDetailPage:function(b,a){window.open("/"+b+"/"+a+".html",b+" details","width=1300, location=no, scrollbars=yes, menubar=no, status=no, titlebar=no, fullscreen=no, toolbar=no").focus();return this},_getProductLineItem:function(b,a,d){var c,e,f,g,k,h;c=this;e=c._uploadedData[d[a]];f=new Element("tr",{"class":"result_row info"});c.csvFileLineFormat.each(function(a){$H(e).each(function(b){b.key===
a&&f.insert({bottom:(new Element("th",{style:b.value?"":"color:red;"})).update(b.value?b.value:"Blank "+a)})})});e.importDataTypes=c._importDataTypes;c.postAjax(c.getCallbackId("getAllCodeForProduct"),e,{onLoading:function(a,c){b.insert({bottom:f})},onSuccess:function(a,d){try{g=c.getResp(d,!1,!0),g.item.id?(f.removeClassName("info").addClassName("result-done").store("data",g.item).down("th"),g.path&&f.down("th").setStyle({cursor:"pointer","text-decoration":"underline"}).observe("click",function(){c._openDetailPage(g.path,
g.item.id)})):f.update("")}catch(h){f.removeClassName("info").addClassName("danger").store("data",e).insert({bottom:(new Element("td",{colspan:2})).update("<strong>ERROR:</strong>"+h)}),b.insert({top:f})}},onComplete:function(e,f){try{k=1*a+1,k>=d.size()?(h=$(c.getHTMLID("importerDiv")).getElementsBySelector(".result_row.danger"),b.up(".panel").removeClassName("panel-danger").addClassName(0<h.size()?"panel-warning":"panel-success").down(".panel-heading").update("").insert({bottom:(new Element("panel-title")).update(0<
h.size()?"All provided rows have been proccessed, but with "+h.size()+" error(s)":"All provided rows have been proccessed successfully")}).insert({bottom:(new Element("span",{"class":"btn-group btn-group-sm pull-right"})).insert({bottom:(new Element("span",{"class":"btn hidden"})).writeAttribute("title",0<h.size()?"Export Success Rows":"Export To Excel").update(new Element("span",{"class":"glyphicon glyphicon-save"})).addClassName(0<h.size()?"btn-warning":"btn-success").observe("click",function(){c.genCSV(this)})}).insert({bottom:(new Element("span",
{"class":"btn btn-default"})).writeAttribute("title","Start Again").update(new Element("span",{"class":"glyphicon glyphicon-repeat"})).observe("click",function(){window.location=document.URL})})})):c._getProductLineItem(b,k,d)}catch(g){alert(g)}}});return c},_loadProductLineItems:function(){var b,a,d;b=[];$H(this._uploadedData).each(function(a){b.push(a.key)});a=new Element("tr");this.csvFileLineFormat.each(function(b){a.insert({bottom:(new Element("th")).update(b)})});$(this.getHTMLID("importerDiv")).update((new Element("div",
{"class":"price_search_result panel panel-danger table-responsive"})).insert({bottom:(new Element("div",{"class":"panel-heading"})).update("Total of <strong>"+b.size()+"</strong> unique row(s) received:").insert({bottom:(new Element("strong",{"class":"pull-right"})).update("please waiting for it to finish")})}).insert({bottom:(new Element("table",{"class":"table table-striped"})).insert({bottom:(new Element("thead")).update(a)}).insert({bottom:d=new Element("tbody")})}));this._getProductLineItem(d,
0,b);return this}});