var BPCPageJs=new Class.create;
BPCPageJs.prototype={modalId:"page_modal_box_id",_htmlIDs:{},_ajaxRequest:null,callbackIds:{},initialize:function(){},setCallbackId:function(a,b){this.callbackIds[a]=b;return this},getCallbackId:function(a){if(void 0===this.callbackIds[a]||null===this.callbackIds[a])throw"Callback ID is not set for:"+a;return this.callbackIds[a]},setHTMLID:function(a,b){this._htmlIDs[a]=b;return this},getHTMLID:function(a){return this._htmlIDs[a]},getFormGroup:function(a,b){return(new Element("div",{"class":"form-group"})).insert({bottom:a.addClassName("control-label")}).insert({bottom:b.addClassName("form-control")})},
postAjax:function(a,b,c,d){this._ajaxRequest=new Prado.CallbackRequest(a,c);this._ajaxRequest.setCallbackParameter(b);a=d||3E4;3E4>a&&(a=3E4);this._ajaxRequest.setRequestTimeOut(a);this._ajaxRequest.dispatch();return this._ajaxRequest},abortAjax:function(){null!==tmp.me._ajaxRequest&&tmp.me._ajaxRequest.abort()},getResp:function(a,b,c){if(!0===(!0!==b?!1:!0))return a;if(a&&a.isJSON()){a=a.evalJSON();if(0!==a.errors.size()){b="Error: \n\n"+a.errors.join("\n");if(!0===c)throw b;return alert(b)}return a.resultData}},
getCurrency:function(a,b,c,d,e){var f,g,h;f=isNaN(c=Math.abs(c))?2:c;b=void 0==b?"$":b;d=void 0==d?".":d;e=void 0==e?",":e;c=0>a?"-":"";g=parseInt(a=Math.abs(+a||0).toFixed(f))+"";h=3<(h=g.length)?h%3:0;return b+c+(h?g.substr(0,h)+e:"")+g.substr(h).replace(/(\d{3})(?=\d)/g,"$1"+e)+(f?d+Math.abs(a-g).toFixed(f).slice(2):"")},getValueFromCurrency:function(a){return a?(a+"").replace(/\s*/g,"").replace(/\$/g,"").replace(/,/g,""):""},keydown:function(a,b,c,d){d=d?d:13;if(!(a.which&&a.which==d||a.keyCode&&
a.keyCode==d))return"function"===typeof c&&c(),!0;"function"===typeof b&&b();return!1},getAlertBox:function(a,b){return(new Element("div",{"class":"alert alert-dismissible",role:"alert"})).insert({bottom:(new Element("button",{"class":"close","data-dismiss":"alert"})).insert({bottom:(new Element("span",{"aria-hidden":"true"})).update("&times;")}).insert({bottom:(new Element("span",{"class":"sr-only"})).update("Close")})}).insert({bottom:(new Element("strong")).update(a)}).insert({bottom:b})},_signRandID:function(a){a.id||
(a.id="input_"+String.fromCharCode(65+Math.floor(26*Math.random()))+Date.now());return this},_markFormGroupError:function(a,b){var c={me:this};a.up(".form-group")&&(a.store("clearErrFunc",function(b){a.up(".form-group").removeClassName("has-error");jQuery("#"+a.id).tooltip("hide").tooltip("destroy").show()}).up(".form-group").addClassName("has-error"),c.me._signRandID(a),jQuery("#"+a.id).tooltip({trigger:"manual",placement:"auto",container:"body",placement:"bottom",html:!0,title:b,content:b}).tooltip("show"),
$(a).observe("change",function(){c.func=$(a).retrieve("clearErrFunc");"function"===typeof c.func&&c.func()}));return c.me},_collectFormData:function(a,b,c){var d,e,f,g,h,k;d=this;e={};f=!1;$(a).getElementsBySelector("["+b+"]").each(function(a){g=c?a.readAttribute(c):null;h=a.readAttribute(b);a.hasAttribute("required")&&$F(a).blank()&&(d._markFormGroupError(a,"This is requried"),f=!0);k="checkbox"!==a.readAttribute("type")?$F(a):$(a).checked;if(a.hasAttribute("validate_currency")||a.hasAttribute("validate_number"))null===
d.getValueFromCurrency(k).match(/^(-)?\d+(\.\d{1,4})?$/)&&(d._markFormGroupError(a,a.hasAttribute("validate_currency")?a.readAttribute("validate_currency"):a.hasAttribute("validate_number")),f=!0),d.getValueFromCurrency(k);null!==g&&void 0!==g?(e[g]||(e[g]={}),e[g][h]=k):e[h]=k});return!0===f?null:e},showModalBox:function(a,b,c,d,e){var f;c=!0===c?!0:!1;d=d?d:null;a=(new Element("div",{"class":"modal",tabindex:"-1",role:"dialog","aria-hidden":"true","aria-labelledby":"page-modal-box"})).insert({bottom:(new Element("div",
{"class":"modal-dialog "+(!0===c?"modal-sm":"modal-lg")})).insert({bottom:(new Element("div",{"class":"modal-content"})).insert({bottom:(new Element("div",{"class":"modal-header"})).insert({bottom:(new Element("div",{"class":"close",type:"button","data-dismiss":"modal"})).insert({bottom:(new Element("span",{"aria-hidden":"true"})).update("&times;")})}).insert({bottom:(new Element("strong",{"class":"modal-title",id:"page-modal-box"})).update(a)})}).insert({bottom:(new Element("div",{"class":"modal-body"})).update(b)}).insert({bottom:null===
d?"":(new Element("div",{"class":"modal-footer"})).update(d)})})});$(this.modalId)&&$(this.modalId).remove();$$("body")[0].insert({bottom:a.writeAttribute("id",this.modalId)});f=jQuery("#"+this.modalId);e&&"object"===typeof e&&$H(e).each(function(a){f.on(a.key,a.value)});f.modal({show:!0,target:"#"+this.modalId});return this},hideModalBox:function(){jQuery("#"+this.modalId).modal("hide");return this},getLoadingImg:function(){return Element("span",{"class":"loading-img fa fa-refresh fa-5x fa-spin"})},
loadUTCTime:function(a){var b;b=a.strip().split(" ");a=b[0].split("-");b=b[1].split(":");return new Date(Date.UTC(a[0],1*a[1]-1,a[2],b[0],b[1],b[2]))},observeClickNDbClick:function(a,b,c){$(a).observe("click",function(d){!0===$(a).retrieve("alreadyclicked")?($(a).store("alreadyclicked",!1),$(a).retrieve("alreadyclickedTimeout")&&clearTimeout($(a).retrieve("alreadyclickedTimeout")),"function"===typeof c&&c(d)):($(a).store("alreadyclicked",!0),$(a).store("alreadyclickedTimeout",setTimeout(function(){$(a).store("alreadyclicked",
!1);"function"===typeof b&&b(d)},300)))});return this},openInNewTab:function(a){window.open(a,"_blank").focus();return this},getUrlParam:function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(location.search);return null===a?"":decodeURIComponent(a[1].replace(/\+/g," "))}};