var PageJs=new Class.create;
PageJs.prototype=Object.extend(new CRUDPageJs,{_getTitleRowData:function(){return{email:"Email",name:"Name",contactNo:"Contact Num",description:"Description",addresses:"Addresses",address:{billing:{full:"Billing Address"},shipping:{full:"Shipping Address"}},mageId:"Mage Id",active:"Active?"}},_bindSearchKey:function(){var a;a=this;$$("#searchBtn").first().observe("click",function(c){$$("#showSearch").first().checked?a.getSearchCriteria().getResults(!0,a._pagination.pageSize):$$("#showSearch").first().click()});
$("searchDiv").getElementsBySelector("[search_field]").each(function(c){c.observe("keydown",function(b){a.keydown(b,function(){$(a.searchDivId).down("#searchBtn").click()})})});return this},_openEditPage:function(a){jQuery.fancybox({width:"95%",height:"95%",autoScale:!1,autoDimensions:!1,fitToView:!1,autoSize:!1,type:"iframe",frameborder:"0",border:"0",seamless:"seamless",href:"/customer/"+(a&&a.id?a.id:"new")+".html"});return this},_highlightSelectedRow:function(a){a=a.down(".glyphicon-plus")?"":
$(a).up("[item_id]").retrieve("data");jQuery(".item_row.success").removeClass("success");jQuery("[item_id="+a.id+"]").addClass("success")},_displaySelectedAddress:function(a){var c,b;c=$(a).up("[item_id]").retrieve("data");b=$(a).down("span").classList.contains("address-shipping");jQuery(".popover-loaded").popover("hide");jQuery(".item_row.success").removeClass("success");jQuery("[item_id="+c.id+"]").addClass("success");this._signRandID(a);jQuery("#"+a.id).hasClass("popover-loaded")||jQuery("#"+a.id).popover({title:'<div class="row"><div class="col-xs-10">Details for: '+
c.name+'</div><div class="col-xs-2" style="cursor: pointer" href="javascript:void(0);" onclick="jQuery(\'#'+a.id+"').popover('hide');\"><span class=\"pull-right glyphicon glyphicon-remove\" ></span></div></div>",html:!0,placement:function(){return b?"left":"right"},container:"body",trigger:"manual",viewport:{selector:".list-panel",padding:0},content:function(){return b?"<p>"+c.address.shipping.full+"</p>":"<p>"+c.address.billing.full+"</p>"},template:'<div class="popover" role="tooltip" style="max-width: none; z-index: 0;"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'}).addClass("popover-loaded");
jQuery("#"+a.id).popover("toggle");return this},_getResultRow:function(a,c){var b={me:this};b.tag=!0===b.isTitle?"th":"td";b.isTitle=c||!1;b.row=(new Element("tr",{"class":(!0===b.isTitle?"item_top_row":"btn-hide-row item_row")+(0==a.active?" danger":""),item_id:!0===b.isTitle?"":a.id})).store("data",a).insert({bottom:(new Element(b.tag,{"class":"name col-xs-1"})).update(a.name).observe("click",function(){b.me._highlightSelectedRow(this);$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")})}).observe("dblclick",
function(){$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")});b.me._openEditPage(a)})}).insert({bottom:(new Element(b.tag,{"class":"email col-xs-1",style:"text-decoration: underline;"})).update(a.email).observe("click",function(){b.me._highlightSelectedRow(this);$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")})}).observe("dblclick",function(){$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")});b.newWindow=window.open("mailto:"+a.email,"width=1300, location=no, scrollbars=yes, menubar=no, status=no, titlebar=no, fullscreen=no, toolbar=no");
b.newWindow.close()})}).insert({bottom:(new Element(b.tag,{"class":"contact col-xs-1 truncate"})).update(a.contactNo)}).insert({bottom:(new Element(b.tag,{"class":"description col-xs-1"})).update(a.description)}).insert({bottom:(new Element(b.tag,{"class":"address col-xs-1"})).insert({bottom:!0===b.isTitle?a.addresses:(new Element("span",{style:"display: inline-block"})).insert({bottom:(new Element("a",{"class":"visible-xs visible-md visible-sm visible-lg",href:"javascript: void(0);"})).insert({bottom:new Element("span",
{"class":"glyphicon glyphicon-plane address-shipping",style:"font-size: 1.3em"})}).observe("click",function(){b.me._displaySelectedAddress(this)})})}).insert({bottom:!0===b.isTitle?"":(new Element("span",{style:"display: inline-block"})).insert({bottom:(new Element("a",{"class":"visible-xs visible-md visible-sm visible-lg",href:"javascript: void(0);"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-usd address-billing",style:"font-size: 1.3em; padding-left:10%;"})}).observe("click",
function(){b.me._displaySelectedAddress(this)})})})}).insert({bottom:(new Element(b.tag,{"class":"mageId col-xs-1"})).update(a.mageId)}).insert({bottom:(new Element(b.tag,{"class":"cust_active col-xs-1"})).insert({bottom:!0===b.isTitle?a.active:new Element("input",{type:"checkbox",disabled:!0,checked:a.active})})}).insert({bottom:(new Element(b.tag,{"class":"text-right col-xs-1"})).update(!0===b.isTitle?(new Element("span",{"class":"btn btn-primary btn-xs",title:"New"})).insert({bottom:new Element("span",
{"class":"glyphicon glyphicon-plus"})}).insert({bottom:" NEW"}).observe("click",function(){$(this).up("thead").insert({bottom:b.me._openEditPage()})}):(new Element("span",{"class":"btn-group btn-group-xs"})).insert({bottom:(new Element("span",{"class":"btn btn-default",title:"Edit"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-pencil"})}).observe("click",function(){$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")});b.me._openEditPage(a)})}).insert({bottom:(new Element("span",
{"class":"btn btn-danger",title:"Delete"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-trash"})}).observe("click",function(){if(!confirm("Are you sure you want to deactivate this item?"))return!1;a.active&&b.me._deactivateItem(this);$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")})})})).observe("click",function(){b.me._highlightSelectedRow(this);$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")})})});return b.row},_getNextPageBtn:function(){var a;
a=this;return(new Element("tfoot")).insert({bottom:(new Element("tr")).insert({bottom:(new Element("td",{colspan:"8","class":"text-center"})).insert({bottom:(new Element("span",{"class":"btn btn-primary","data-loading-text":"Fetching more results ..."})).update("Show More").observe("click",function(){a._pagination.pageNo=1*a._pagination.pageNo+1;jQuery(this).button("loading");a.getResults()})})})})},_deactivateItem:function(a){var c,b,d;c=this;b=$(a).up("[item_id]");a=b.retrieve("data");c.postAjax(c.getCallbackId("deactivateItems"),
{item_id:a.id},{onCreate:function(){b&&(b.toggleClassName("danger"),b.hide())},onSuccess:function(a,e){try{b.toggleClassName("danger");d=c.getResp(e,!1,!0);if(!d.item)throw"errror";$$('[item_id="'+d.item.id+'"]').first().replace(c._getResultRow(d.item,!1));c._highlightSelectedRow($$('[item_id="'+d.item.id+'"]').first().down(".glyphicon.glyphicon-trash"))}catch(f){c.showModalBox('<span class="text-danger">ERROR</span>',f,!0)}}})}});