var PageJs=new Class.create;
PageJs.prototype=Object.extend(new CRUDPageJs,{_getTitleRowData:function(){return{totalAmount:"PO Amount Inc. GST",totalReceivedValue:"Bill Amount Inc. GST",totalPaid:"Total Paid",purchaseOrderNo:"PO Number",supplier:{name:"Supplier"},status:"Status",supplierRefNo:"PO Ref.",orderDate:"Order Date",active:"Active"}},_loadChosen:function(){jQuery(".chosen").chosen({disable_search_threshold:10,no_results_text:"Oops, nothing found!",width:"95%"});jQuery('.chosen-container input[type="text"]').keydown(function(b){if(13==b.which||
13==b.keyCode)b.preventDefault(),$("searchPanel").down("#searchBtn").click()});return this},_bindSearchKey:function(){var b,c,a,d;b=this;$$("#searchBtn").first().observe("click",function(a){$$("#showSearch").first().checked?b.getSearchCriteria().getResults(!0,b._pagination.pageSize):$$("#showSearch").first().click()});c=(new Element("input",{"class":"select2 form-control","data-placeholder":"the Name of Supplier",search_field:"po.supplierIds"})).insert({bottom:(new Element("option")).update("")});
$(b.searchDivId).down('[search_field="po.supplierIds"]').replace(c);jQuery('.select2[search_field="po.supplierIds"]').select2({allowClear:!0,hidden:!0,multiple:!0,ajax:{url:"/ajax/getSuppliers",dataType:"json",delay:10,data:function(a){return{searchTxt:a}},results:function(b){a=[];b.resultData.items.each(function(b){a.push({id:b.id,text:b.name,data:b})});return{results:a}},cache:!0},formatResult:function(a){return a?"<div value="+a.data.id+">"+a.data.name+"</div >":""},escapeMarkup:function(a){return a},
minimumInputLength:1});c=new Element("select",{"class":"select2 form-control",multiple:!0,"data-placeholder":"the Status of PO",search_field:"po.status"});b._status.each(function(a){c.insert({bottom:d=(new Element("option",{value:a})).update(a)});"NEW"!==a&&"ORDERED"!==a&&"RECEIVING"!==a||d.writeAttribute("selected",!0)});$(b.searchDivId).down('[search_field="po.status"]').replace(c);jQuery('.select2[search_field="po.status"]').select2({allowClear:!0,hidden:!0});c=(new Element("input",{"class":"select2 form-control",
"data-placeholder":"search for a Products",search_field:"pro.ids"})).insert({bottom:(new Element("option")).update("")});$("searchDiv").down('[search_field="pro.ids"]').replace(c);jQuery('.select2[search_field="pro.ids"]').select2({allowClear:!0,hidden:!0,multiple:!0,ajax:{url:"/ajax/getProducts",dataType:"json",delay:10,data:function(a){return{searchTxt:a,pageNo:1,pageSize:10}},results:function(b){a=[];b.resultData.items.each(function(b){a.push({id:b.id,text:b.name,data:b})});return{results:a}},
cache:!0},formatResult:function(a){return a?"<div value="+a.data.id+">"+a.data.name+"</div >":""},escapeMarkup:function(a){return a},minimumInputLength:3});$("searchDiv").getElementsBySelector("[search_field]").each(function(a){a.observe("keydown",function(a){b.keydown(a,function(){$(b.searchDivId).down("#searchBtn").click()})})});return this},_loadDataPicker:function(){$$(".datepicker").each(function(b){new Prado.WebUI.TDatePicker({ID:b,InputMode:"TextBox",Format:"yyyy-MM-dd 00:00:00",FirstDayOfWeek:1,
CalendarStyle:"default",FromYear:2009,UpToYear:2024,PositionMode:"Bottom",ClassName:"datepicker-layer-fixer"})});return this},getResults:function(b,c){var a,d,e,f,g;a=this;d=b||!1;e=$(a.resultDivId);!0===d&&(a._pagination.pageNo=1);a._pagination.pageSize=c||a._pagination.pageSize;a.postAjax(a.getCallbackId("getItems"),{pagination:a._pagination,searchCriteria:a._searchCriteria},{onCreate:function(){jQuery("#"+a.searchDivId+" #searchBtn").button("loading");!0===d&&e.update((new Element("tr")).update((new Element("td")).update(a.getLoadingImg())))},
onSuccess:function(b,c){try{if(f=a.getResp(c,!1,!0))$(a.totalNoOfItemsId).update(f.pageStats.totalRows),!0===d&&e.update(a._getResultRow(a._getTitleRowData(),!0).wrap(new Element("thead"))),e.getElementsBySelector(".paginWrapper").each(function(a){a.remove()}),(g=$(e).down("tbody"))||$(e).insert({bottom:g=new Element("tbody")}),f.items.each(function(b){b.item.totalProdcutCount=b.totalProdcutCount;b=b.item;g.insert({bottom:a._getResultRow(b).addClassName("item_row").writeAttribute("item_id",b.id)})}),
f.pageStats.pageNumber<f.pageStats.totalPages&&e.insert({bottom:a._getNextPageBtn().addClassName("paginWrapper")})}catch(h){e.insert({bottom:a.getAlertBox("Error",h).addClassName("alert-danger")})}},onComplete:function(){jQuery("#"+a.searchDivId+" #searchBtn").button("reset")}})},_deactivateItem:function(b){var c,a,d;c=this;a=$$('[item_id="'+b.id+'"]').first();c.postAjax(c.getCallbackId("deactivateItems"),{item_id:b.id},{onCreate:function(){a&&a.hide();c.hideModalBox()},onSuccess:function(b,f){try{a.toggleClassName("danger");
d=c.getResp(f,!1,!0);if(!d.item)throw"errror";a.replace(c._getResultRow(d.item,!1))}catch(g){c.showModalBox('<span class="text-danger">ERROR</span>',g,!0)}},onComplete:function(){a&&a.show()}})},_shoConfirmDel:function(b){var c,a;c=this;a=(new Element("div")).insert({bottom:(new Element("strong")).update("You are about to delete a Purchase Order: "+b.purchaseOrderNo)}).insert({bottom:(new Element("strong")).update("After confirming deletion:")}).insert({bottom:(new Element("ul")).insert({bottom:(new Element("li")).update(" - All received item will be deleted, and stock will be reverted from StockOnHand to StockOnPO.")}).insert({bottom:(new Element("li")).update(" - This PO will be dactivated.")})}).insert({bottom:(new Element("div")).update((new Element("strong")).update("Are you sure you want to continue?"))}).insert({bottom:(new Element("div")).insert({bottom:(new Element("span",
{"class":"btn btn-danger"})).update("YES, deactivate it").observe("click",function(){c._deactivateItem(b)})}).insert({bottom:(new Element("span",{"class":"btn btn-default pull-right"})).update("NO, cancel this").observe("click",function(){c.hideModalBox()})})});c.showModalBox('<strong class="text-warning">Confirm</strong>',a);return c},_getResultRow:function(b,c){var a={me:this};a.tag=!0===a.isTitle?"th":"td";a.isTitle=c||!1;a.invoiceNoDiv=new Element("div");c||b.supplierInvoices.each(function(b){a.invoiceNoDiv.insert({bottom:(new Element("div")).update(b)})});
a.row=(new Element("tr",{"class":(!0===a.isTitle?"item_top_row":"btn-hide-row item_row po_item")+(0==b.active?" danger":""),item_id:!0===a.isTitle?"":b.id})).store("data",b).insert({bottom:(new Element(a.tag,{"class":"purchaseOrderNo col-xs-1"})).update(a.isTitle?b.purchaseOrderNo:(new Element("a",{href:"/purchase/"+b.id+".html",target:"_BLANK"})).update(b.purchaseOrderNo))}).insert({bottom:(new Element(a.tag,{"class":" col-xs-1"})).update(a.me.loadUTCTime(b.orderDate).toLocaleString())}).insert({bottom:(new Element(a.tag,
{"class":" col-xs-1"})).update(b.supplier.name?b.supplier.name:"")}).insert({bottom:(new Element(a.tag,{"class":" col-xs-1"})).update(a.isTitle?"Invoice No(s)":b.totalPaid?a.invoiceNoDiv:"")}).insert({bottom:(new Element(a.tag,{"class":" col-xs-1"})).update(b.supplierRefNo?b.supplierRefNo:"")}).insert({bottom:(new Element(a.tag,{"class":" col-xs-1"})).update(a.isTitle?"Products Count":(new Element("a",{href:"/serialnumbers.html?purchaseorderid="+b.id,target:"_BLANK"})).insert({bottom:(new Element("abbr",
{title:"Received Product Count on this PO"})).update(b.totalReceivedCount)}).insert({bottom:(new Element("span")).update(" / ")}).insert({bottom:(new Element("abbr",{title:"Total Product Count on this PO"})).update(b.totalProductCount)}))}).insert({bottom:(new Element(a.tag,{"class":" col-xs-1"})).update(a.isTitle?"ETA":b.eta?a.me.loadUTCTime(b.eta).toDateString():"")}).insert({bottom:(new Element(a.tag,{"class":" col-xs-1"})).update(a.isTitle?b.totalAmount:a.me.getCurrency(b.totalAmount))}).insert({bottom:(new Element(a.tag,
{"class":" col-xs-1"})).update(a.isTitle?b.totalReceivedValue:a.me.getCurrency(1.1*b.totalReceivedValue))}).insert({bottom:(new Element(a.tag,{"class":" col-xs-1"})).update(a.isTitle?"Total Paid":b.totalPaid?a.me.getCurrency(b.totalPaid):"")}).insert({bottom:(new Element(a.tag,{"class":" col-xs-1",order_status:b.status})).update(b.status)}).insert({bottom:a.btns=new Element(a.tag,{"class":"col-xs-1 text-right"})});!0!==a.isTitle&&a.btns.insert({bottom:(new Element("div",{"class":"btn-group"})).insert({bottom:!b.id||
"ORDERED"!==b.status&&"RECEIVING"!==b.status||!0!==b.active?"":(new Element("a",{"class":"btn btn-success btn-xs",href:"/receiving/"+b.id+".html",target:"_BLANK",title:"Receiving Items"})).update("Receiving")}).insert({bottom:(new Element("a",{"class":"btn btn-default btn-xs",title:"Edit",href:"/purchase/"+b.id+".html",target:"_BLANK"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-pencil"})})}).insert({bottom:(new Element("span",{"class":"btn btn-danger btn-xs",title:"Delete"})).insert({bottom:new Element("span",
{"class":"glyphicon glyphicon-trash"})}).observe("click",function(){a.me._shoConfirmDel(b)})})});return a.row}});