ALTER TABLE `customer` ADD `isFromB2B` tinyint(1) NOT NULL DEFAULT '0' AFTER `mageId` , ADD INDEX ( `isFromB2B` );

ALTER TABLE `product` ADD `stockOnOrder` int(10) NOT NULL DEFAULT '0' AFTER `stockOnHand` , ADD INDEX ( `stockOnOrder` );
ALTER TABLE `product` ADD `shortDescription` varchar(255) NOT NULL DEFAULT '' AFTER `isFromB2B` , ADD INDEX ( `shortDescription` );
ALTER TABLE `product` ADD `fullDescAssetId` varchar(100) NOT NULL DEFAULT '' AFTER `shortDescription` , ADD INDEX ( `fullDescAssetId` );

ALTER TABLE `product` MODIFY COLUMN `sku`varchar(50) NOT NULL DEFAULT ''; 
ALTER TABLE `product` MODIFY COLUMN `name` varchar(100) NOT NULL DEFAULT ''; 


ALTER TABLE `customer` ADD INDEX ( `created` );
ALTER TABLE `customer` ADD INDEX ( `updated` );
ALTER TABLE `customer` ADD INDEX ( `active` );

insert into systemsettings (`type`, `value`, `description`, `active`, `created`, `createdById`, `updated`, `updatedById`)
values('asset_root_dir', '/var/www/html/contents/', 'The root directory of the assets', 1, NOW(), 1, NOW(), 1);


CREATE TABLE `manufacturer` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `mageId`  int(10) unsigned NOT NULL DEFAULT '0',
  `isFromB2B` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `mageId` (`mageId`),
  KEY `isFromB2B` (`isFromB2B`),
  KEY `name` (`name`),
  KEY `description` (`description`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

insert into `manufacturer`(`name`, `description`, `active`, `created`, `createdById`, `updated`,`updatedById`) values 
    ('A-RAM', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Acer', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Adaptec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ADATA', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Adobe', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ADS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Aereon', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Aiptek', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Alogic', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ALOGIC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Alphacool', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('AMACROX', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('AMD', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Antec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ANYWARE', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('AOC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Apacer', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('APC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('APPLE', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ARCTIC COOLING', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Asrock', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Astrotek', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Asus', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ATEN', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('AVerMedia', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Aywun', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('BENQ', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Billion', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Bitfenix', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('BlueAnt', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('BRATECK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Brother', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Budget PC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Canon', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('CHERRY', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('CISCO', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Clickfree', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Cooler Master', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Corsair', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Creative', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('CYBERLINK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('CyberPower', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('DATALOGIC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('DeepCool', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Dell', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Dlink', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('DrayTek', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Eaton', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ECS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Edifier', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('EDIMAX', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Elixir', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Epson', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('EVERKI', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('EVGA', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Foxconn', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('FRACTAL DESIGN', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('FSP', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Fuji-Xerox', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('FUJITSU', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('G.Skill', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('GAINWARD', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Galaxy', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Gateway', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Gigabyte', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Gigazone', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Gigazone international Co.LTD.', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('GlacialTech', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Gunnar', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Hallam', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Hauppauge', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Havit', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('HIS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Hitachi', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('HP', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('HUNTKEY', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Hytec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Hyundai', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('IBM', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Intel', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Iogear', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('IOGEAR', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ioSafe', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('iWALK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('KASPERSKY LAB', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('KENSINGTON', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Kingston', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Konica', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Koolance', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Kyocera', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('LACIE', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Laice', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lanier', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Laser', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('LEADTEK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lemel', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lenovo', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lexmark', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('LG', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lian Li', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('LINKSYS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lite-On', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Logitech', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('MATROX', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Maxtron', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('MICROJET', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Microlab', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Microsoft', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Microsoft (ESD)', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Mitsubishi', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Motorola', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('MSI', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Navigon', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NEC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NERO', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NETCOMM', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Netgear', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Noctua', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Nokia', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NORTON', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NVIDIA', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NZXT', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('OCZ', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('oki', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('OLYMPUS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('OPTIMA', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Palit Microsystems Limited.', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('PANASONIC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Patriot', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('PHILIPS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('PINNACLE', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('PIONEER', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Plantronics', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Plextor', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Power Color', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('QNAP', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Quantum', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Razer', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Repotec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Samsung', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SanDisk', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Sansai', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SAPPHIRE', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Seagate', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Seltec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Serveredge', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Sharp', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SHINTARO', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Shuttle', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Siemens', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SilverStone', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Sony', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Steel Series', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SUNIX', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SYMANTEC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SYNOLOGY', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Targus', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('TEAC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('TEAM', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('TECXUS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Telstra', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Thecus', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Thermalright', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Thermaltake', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Thermolab', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Toshiba', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('TP-LINK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Transcend', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('TREND MICRO', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('UPSONIC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('UTEPO', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('VANTEC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('VERBATIM', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ViewSonic', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Vivotek', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('WELLAND', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Western Digital', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Wyse', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('X-mini', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Xerox', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('XFX', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('XIGMATEK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Zalman', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10);

CREATE TABLE `productcode` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `productId` int(10) unsigned NOT NULL DEFAULT '0',
  `typeId` int(10) unsigned NOT NULL DEFAULT '0',
  `code` varchar(100) NOT NULL DEFAULT '',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `productId` (`productId`),
  KEY `typeId` (`typeId`),
  KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `productcodetype` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `allowMultiple` tinyint(1) NOT NULL DEFAULT '1',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `name` (`name`),
  KEY `description` (`description`),
  KEY `allowMultiple` (`allowMultiple`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `productimage` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `productId` int(10) unsigned NOT NULL DEFAULT '0',
  `imageAssetId` varchar(32) NOT NULL DEFAULT '',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `imageAssetId` (`imageAssetId`),
  KEY `productId` (`productId`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `supplier` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `contactName` varchar(100) NOT NULL DEFAULT '',
  `contactNo` varchar(100) NOT NULL DEFAULT '',
  `addressId`  int(10) unsigned NULL DEFAULT null,
  `mageId`  int(10) unsigned NOT NULL DEFAULT '0',
  `isFromB2B` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `mageId` (`mageId`),
  KEY `isFromB2B` (`isFromB2B`),
  KEY `name` (`name`),
  KEY `description` (`description`),
  KEY `contactName` (`contactName`),
  KEY `contactNo` (`contactNo`),
  KEY `addressId` (`addressId`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
insert into `supplier`(`name`, `description`, `active`, `created`, `createdById`, `updated`,`updatedById`) values 
    ('anyware', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('australiait', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('bluechip', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('budgetpc', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('dickerdata', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Ingram', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('mittoni', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('mmt', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('seltec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('synnex', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('tonnex', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10);


CREATE TABLE `suppliercode` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `productId` int(10) unsigned NOT NULL DEFAULT '0',
  `supplierId` int(10) unsigned NOT NULL DEFAULT '0',
  `code` varchar(100) NOT NULL DEFAULT '',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `productId` (`productId`),
  KEY `supplierId` (`supplierId`),
  KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `productcategory` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `rootId` int(10) unsigned NULL DEFAULT NULL,
  `parentId` int(10) unsigned NULL DEFAULT NULL,
  `position` varchar(255) NOT NULL DEFAULT '',
  `mageId`  int(10) unsigned NOT NULL DEFAULT '0',
  `isFromB2B` tinyint(1) NOT NULL DEFAULT '0',
  `isAnchor` tinyint(1) NOT NULL DEFAULT '0',
  `includeInMenu` tinyint(1) NOT NULL DEFAULT '0',
  `urlKey` varchar(50) NOT NULL DEFAULT '',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `name` (`name`),
  KEY `rootId` (`rootId`),
  KEY `parentId` (`parentId`),
  KEY `position` (`position`),
  KEY `mageId` (`mageId`),
  KEY `isFromB2B` (`isFromB2B`),
  KEY `isAnchor` (`isAnchor`),
  KEY `includeInMenu` (`includeInMenu`),
  KEY `urlKey` (`urlKey`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `product_category` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `productId` int(10) unsigned NOT NULL DEFAULT '0',
  `categoryId` int(10) unsigned NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `productId` (`productId`),
  KEY `categoryId` (`categoryId`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE `product` DROP `price`, DROP INDEX `price`;



CREATE TABLE `productpricetype` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `needTime` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `name` (`name`),
  KEY `needTime` (`needTime`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
insert into `productpricetype` (`id`, `name`, `description`, `needTime`, `active`, `created`, `createdById`, `updated`, `updatedById`) values
	(1, 'Retail Price', 'Recommended Retail Price / Normal sales price', 0, 1, NOW(), 10, NOW(), 10),
	(2, 'Casual Special Price', 'Promotional purpose sepcial price',1,  1, NOW(), 10, NOW(), 10),
	(3, 'Special Price Group 1', 'Special Price For Group 1 Customers',0,  1, NOW(), 10, NOW(), 10),
	(4, 'Special Price Group 2', 'Special Price For Group 2 Customers',0,  1, NOW(), 10, NOW(), 10);
	
	
CREATE TABLE `productprice` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `productId` int(10) unsigned NOT NULL DEFAULT '0',
  `typeId` int(10) unsigned NOT NULL DEFAULT '0',
  `price` double(10,4) unsigned NOT NULL DEFAULT '0.0000',
  `start` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `end` datetime NOT NULL DEFAULT '9999-12-31 23:59:59',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `productId` (`productId`),
  KEY `typeId` (`typeId`),
  KEY `price` (`price`),
  KEY `start` (`start`),
  KEY `end` (`end`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `productstatus` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

insert into `productstatus` (`id`, `name`, `description`, `active`, `created`, `createdById`, `updated`, `updatedById`) values
    (1, 'Back Order Only', 'Status for Any Back Order', 1, NOW(), 10, NOW(), 10),
    (2, 'In Stock', 'For products that we have stock', 1, NOW(), 10, NOW(), 10),
    (3, 'Pre Order', 'For produts that we have No stock', 1, NOW(), 10, NOW(), 10),
    (4, 'Ships in 24 Hrs', 'For produts that we have No stock but can ship in 24 hrs', 1, NOW(), 10, NOW(), 10),
    (5, 'Low Stock', 'For produts that low quantity on stock', 1, NOW(), 10, NOW(), 10);


ALTER TABLE `product` ADD `sellOnWeb` TINYINT( 1 ) NOT NULL DEFAULT '0' AFTER `isFromB2B`, add index (`sellOnWeb`);
ALTER TABLE `product` ADD `statusId` int(10) unsigned NULL DEFAULT NULL AFTER `sellOnWeb`, add index (`statusId`);
ALTER TABLE `product` ADD `manufacturerId` int(10) unsigned NULL DEFAULT NULL AFTER `statusId`, add index (`manufacturerId`);
ALTER TABLE `product` ADD `asNewFromDate` datetime NULL DEFAULT null AFTER `manufacturerId`, add index (`asNewFromDate`);
ALTER TABLE `product` ADD `asNewToDate` datetime NULL DEFAULT null AFTER `asNewFromDate`, add index (`asNewToDate`);

insert into `productinfotype` (`id`, `name`, `active`, `created`, `createdById`, `updated`, `updatedById`) values
     (2, 'Weight',  1, NOW(), 10, NOW(), 10);
