ALTER TABLE `customer` ADD `isFromB2B` tinyint(1) NOT NULL DEFAULT '0' AFTER `mageId` , ADD INDEX ( `isFromB2B` );

ALTER TABLE `product` ADD `stockOnOrder` int(10) NOT NULL DEFAULT '0' AFTER `stockOnHand` , ADD INDEX ( `stockOnOrder` );
ALTER TABLE `product` ADD `shortDescription` varchar(255) NOT NULL DEFAULT '' AFTER `isFromB2B` , ADD INDEX ( `shortDescription` );
ALTER TABLE `product` ADD `fullDescAssetId` varchar(100) NOT NULL DEFAULT '' AFTER `shortDescription` , ADD INDEX ( `fullDescAssetId` );

ALTER TABLE `product` MODIFY COLUMN `sku`varchar(50) NOT NULL DEFAULT ''; 
ALTER TABLE `product` MODIFY COLUMN `name` varchar(100) NOT NULL DEFAULT ''; 


ALTER TABLE `customer` ADD INDEX ( `created` );
ALTER TABLE `customer` ADD INDEX ( `updated` );
ALTER TABLE `customer` ADD INDEX ( `active` );

insert into systemsettings (`type`, `value`, `description`, `active`, `created`, `createdById`, `updated`, `updatedById`)
values('asset_root_dir', '/var/www/html/contents/', 'The root directory of the assets', 1, NOW(), 1, NOW(), 1);


CREATE TABLE `manufacturer` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `mageId`  int(10) unsigned NOT NULL DEFAULT '0',
  `isFromB2B` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `mageId` (`mageId`),
  KEY `isFromB2B` (`isFromB2B`),
  KEY `name` (`name`),
  KEY `description` (`description`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

insert into `manufacturer`(`name`, `description`, `active`, `created`, `createdById`, `updated`,`updatedById`) values 
    ('A-RAM', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Acer', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Adaptec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ADATA', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Adobe', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ADS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Aereon', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Aiptek', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Alogic', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ALOGIC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Alphacool', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('AMACROX', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('AMD', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Antec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ANYWARE', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('AOC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Apacer', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('APC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('APPLE', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ARCTIC COOLING', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Asrock', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Astrotek', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Asus', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ATEN', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('AVerMedia', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Aywun', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('BENQ', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Billion', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Bitfenix', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('BlueAnt', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('BRATECK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Brother', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Budget PC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Canon', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('CHERRY', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('CISCO', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Clickfree', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Cooler Master', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Corsair', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Creative', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('CYBERLINK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('CyberPower', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('DATALOGIC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('DeepCool', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Dell', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Dlink', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('DrayTek', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Eaton', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ECS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Edifier', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('EDIMAX', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Elixir', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Epson', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('EVERKI', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('EVGA', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Foxconn', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('FRACTAL DESIGN', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('FSP', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Fuji-Xerox', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('FUJITSU', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('G.Skill', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('GAINWARD', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Galaxy', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Gateway', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Gigabyte', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Gigazone', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Gigazone international Co.LTD.', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('GlacialTech', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Gunnar', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Hallam', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Hauppauge', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Havit', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('HIS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Hitachi', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('HP', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('HUNTKEY', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Hytec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Hyundai', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('IBM', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Intel', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Iogear', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('IOGEAR', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ioSafe', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('iWALK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('KASPERSKY LAB', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('KENSINGTON', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Kingston', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Konica', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Koolance', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Kyocera', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('LACIE', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Laice', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lanier', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Laser', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('LEADTEK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lemel', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lenovo', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lexmark', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('LG', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lian Li', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('LINKSYS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Lite-On', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Logitech', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('MATROX', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Maxtron', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('MICROJET', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Microlab', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Microsoft', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Microsoft (ESD)', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Mitsubishi', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Motorola', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('MSI', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Navigon', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NEC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NERO', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NETCOMM', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Netgear', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Noctua', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Nokia', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NORTON', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NVIDIA', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('NZXT', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('OCZ', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('oki', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('OLYMPUS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('OPTIMA', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Palit Microsystems Limited.', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('PANASONIC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Patriot', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('PHILIPS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('PINNACLE', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('PIONEER', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Plantronics', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Plextor', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Power Color', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('QNAP', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Quantum', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Razer', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Repotec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Samsung', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SanDisk', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Sansai', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SAPPHIRE', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Seagate', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Seltec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Serveredge', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Sharp', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SHINTARO', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Shuttle', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Siemens', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SilverStone', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Sony', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Steel Series', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SUNIX', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SYMANTEC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('SYNOLOGY', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Targus', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('TEAC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('TEAM', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('TECXUS', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Telstra', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Thecus', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Thermalright', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Thermaltake', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Thermolab', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Toshiba', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('TP-LINK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Transcend', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('TREND MICRO', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('UPSONIC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('UTEPO', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('VANTEC', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('VERBATIM', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('ViewSonic', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Vivotek', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('WELLAND', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Western Digital', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Wyse', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('X-mini', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Xerox', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('XFX', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('XIGMATEK', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Zalman', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10);

CREATE TABLE `productcode` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `productId` int(10) unsigned NOT NULL DEFAULT '0',
  `typeId` int(10) unsigned NOT NULL DEFAULT '0',
  `code` varchar(100) NOT NULL DEFAULT '',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `productId` (`productId`),
  KEY `typeId` (`typeId`),
  KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `productcodetype` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `allowMultiple` tinyint(1) NOT NULL DEFAULT '1',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `name` (`name`),
  KEY `description` (`description`),
  KEY `allowMultiple` (`allowMultiple`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `productimage` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `productId` int(10) unsigned NOT NULL DEFAULT '0',
  `imageAssetId` varchar(20) NOT NULL DEFAULT '',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `imageAssetId` (`imageAssetId`),
  KEY `productId` (`productId`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `supplier` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `contactName` varchar(100) NOT NULL DEFAULT '',
  `contactNo` varchar(100) NOT NULL DEFAULT '',
  `addressId`  int(10) unsigned NULL DEFAULT null,
  `mageId`  int(10) unsigned NOT NULL DEFAULT '0',
  `isFromB2B` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `mageId` (`mageId`),
  KEY `isFromB2B` (`isFromB2B`),
  KEY `name` (`name`),
  KEY `description` (`description`),
  KEY `contactName` (`contactName`),
  KEY `contactNo` (`contactNo`),
  KEY `addressId` (`addressId`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
insert into `supplier`(`name`, `description`, `active`, `created`, `createdById`, `updated`,`updatedById`) values 
    ('anyware', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('australiait', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('bluechip', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('budgetpc', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('dickerdata', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('Ingram', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('mittoni', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('mmt', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('seltec', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('synnex', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10),
    ('tonnex', 'From BudgetPC Magento', 1, NOW(), 10, NOW(), 10);


CREATE TABLE `suppliercode` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `productId` int(10) unsigned NOT NULL DEFAULT '0',
  `supplierId` int(10) unsigned NOT NULL DEFAULT '0',
  `code` varchar(100) NOT NULL DEFAULT '',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `productId` (`productId`),
  KEY `supplierId` (`supplierId`),
  KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `productcategory` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `rootId` int(10) unsigned NULL DEFAULT NULL,
  `parentId` int(10) unsigned NULL DEFAULT NULL,
  `position` varchar(255) NOT NULL DEFAULT '',
  `mageId`  int(10) unsigned NOT NULL DEFAULT '0',
  `isFromB2B` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `name` (`name`),
  KEY `rootId` (`rootId`),
  KEY `parentId` (`parentId`),
  KEY `position` (`position`),
  KEY `mageId` (`mageId`),
  KEY `isFromB2B` (`isFromB2B`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

insert into `productcategory` (`name`, `description`, `parentId`, `rootId`,`active`, `created`, `createdById`, `updated`, `updatedById`) values
	('2014 EOFY SALE', '2014 EOFY SALE', NULL, 1, 1, NOW(), 10, NOW(),10),
	('Apple', 'Apple', NULL, 2, 1, NOW(), 10, NOW(),10),
	('Budget PC Recommand', 'Budget PC Recommand', NULL, 3, 1, NOW(), 10, NOW(),10),
	('Cisco', 'Cisco', NULL, 4, 1, NOW(), 10, NOW(),10),
	('Computer Hardware', 'Computer Hardware', NULL, 5, 1, NOW(), 10, NOW(),10),
	('Computers & Servers', 'Computers & Servers', NULL, 6, 1, NOW(), 10, NOW(),10),
	('Disabled Products', 'Disabled Products', NULL, 7, 1, NOW(), 10, NOW(),10),
	('New Computers', 'New Computers', NULL, 8, 1, NOW(), 10, NOW(),10),
	('New Notebooks', 'New Notebooks', NULL, 9, 1, NOW(), 10, NOW(),10),
	('New Products', 'New Products', NULL, 10, 1, NOW(), 10, NOW(),10),
	('Notebooks & Tablets', 'Notebooks & Tablets', NULL, 11, 1, NOW(), 10, NOW(),10),
	('Refurbished Products', 'Refurbished Products', NULL, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Products', 'Refurbished Products', NULL, 13, 1, NOW(), 10, NOW(),10),
	('Software', 'Software', NULL, 14, 1, NOW(), 10, NOW(),10),
	('Special Products', 'Special Products', NULL, 15, 1, NOW(), 10, NOW(),10),
	('EOFY Sale Deskop', 'EOFY Sale Deskop', 1, 1, 1, NOW(), 10, NOW(),10),
	('EOFY Sale Notebook and Tablet ', 'EOFY Sale Notebook and Tablet ', 1, 1, 1, NOW(), 10, NOW(),10),
	('Accessories', 'Accessories', 5, 5, 1, NOW(), 10, NOW(),10),
	('Networking', 'Networking', 5, 5, 1, NOW(), 10, NOW(),10),
	('PC Components', 'PC Components', 5, 5, 1, NOW(), 10, NOW(),10),
	('Peripherals', 'Peripherals', 5, 5, 1, NOW(), 10, NOW(),10),
	('Printing', 'Printing', 5, 5, 1, NOW(), 10, NOW(),10),
	('Storage Devices', 'Storage Devices', 5, 5, 1, NOW(), 10, NOW(),10),
	('Adapters & Converters', 'Adapters & Converters', 18, 5, 1, NOW(), 10, NOW(),10),
	('Add-On Cards', 'Add-On Cards', 18, 5, 1, NOW(), 10, NOW(),10),
	('Batteries', 'Batteries', 18, 5, 1, NOW(), 10, NOW(),10),
	('Cable Management', 'Cable Management', 18, 5, 1, NOW(), 10, NOW(),10),
	('Cables', 'Cables', 18, 5, 1, NOW(), 10, NOW(),10),
	('Card Readers', 'Card Readers', 18, 5, 1, NOW(), 10, NOW(),10),
	('Hubs', 'Hubs', 18, 5, 1, NOW(), 10, NOW(),10),
	('Apple Adapters', 'Apple Adapters', 24, 5, 1, NOW(), 10, NOW(),10),
	('Display Port', 'Display Port', 24, 5, 1, NOW(), 10, NOW(),10),
	('DVI', 'DVI', 24, 5, 1, NOW(), 10, NOW(),10),
	('HDMI', 'HDMI', 24, 5, 1, NOW(), 10, NOW(),10),
	('Power', 'Power', 24, 5, 1, NOW(), 10, NOW(),10),
	('USB', 'USB', 24, 5, 1, NOW(), 10, NOW(),10),
	('VGA', 'VGA', 24, 5, 1, NOW(), 10, NOW(),10),
	('VGA Splitters', 'VGA Splitters', 24, 5, 1, NOW(), 10, NOW(),10),
	('Audio', 'Audio', 28, 5, 1, NOW(), 10, NOW(),10),
	('Display Port', 'Display Port', 28, 5, 1, NOW(), 10, NOW(),10),
	('DVI', 'DVI', 28, 5, 1, NOW(), 10, NOW(),10),
	('Fiber Optic', 'Fiber Optic', 28, 5, 1, NOW(), 10, NOW(),10),
	('Firewire', 'Firewire', 28, 5, 1, NOW(), 10, NOW(),10),
	('HDMI', 'HDMI', 28, 5, 1, NOW(), 10, NOW(),10),
	('IDE', 'IDE', 28, 5, 1, NOW(), 10, NOW(),10),
	('KVM', 'KVM', 28, 5, 1, NOW(), 10, NOW(),10),
	('Network', 'Network', 28, 5, 1, NOW(), 10, NOW(),10),
	('Parallel (Printer)', 'Parallel (Printer)', 28, 5, 1, NOW(), 10, NOW(),10),
	('Power', 'Power', 28, 5, 1, NOW(), 10, NOW(),10),
	('RCA', 'RCA', 28, 5, 1, NOW(), 10, NOW(),10),
	('Sata / eSata', 'Sata / eSata', 28, 5, 1, NOW(), 10, NOW(),10),
	('SCSI / SAS', 'SCSI / SAS', 28, 5, 1, NOW(), 10, NOW(),10),
	('Serial', 'Serial', 28, 5, 1, NOW(), 10, NOW(),10),
	('USB', 'USB', 28, 5, 1, NOW(), 10, NOW(),10),
	('VGA', 'VGA', 28, 5, 1, NOW(), 10, NOW(),10),
	('Access Points', 'Access Points', 19, 5, 1, NOW(), 10, NOW(),10),
	('Antennas', 'Antennas', 19, 5, 1, NOW(), 10, NOW(),10),
	('Bluetooth', 'Bluetooth', 19, 5, 1, NOW(), 10, NOW(),10),
	('Ethernet Adapters', 'Ethernet Adapters', 19, 5, 1, NOW(), 10, NOW(),10),
	('Fibre & Media Converters', 'Fibre & Media Converters', 19, 5, 1, NOW(), 10, NOW(),10),
	('Firewalls', 'Firewalls', 19, 5, 1, NOW(), 10, NOW(),10),
	('IP / Network Cameras', 'IP / Network Cameras', 19, 5, 1, NOW(), 10, NOW(),10),
	('Modems', 'Modems', 19, 5, 1, NOW(), 10, NOW(),10),
	('Patch Panels', 'Patch Panels', 19, 5, 1, NOW(), 10, NOW(),10),
	('Powerline Adapters & Kits', 'Powerline Adapters & Kits', 19, 5, 1, NOW(), 10, NOW(),10),
	('Printer Servers', 'Printer Servers', 19, 5, 1, NOW(), 10, NOW(),10),
	('Range Extenders', 'Range Extenders', 19, 5, 1, NOW(), 10, NOW(),10),
	('Routers', 'Routers', 19, 5, 1, NOW(), 10, NOW(),10),
	('Server Cabinets', 'Server Cabinets', 19, 5, 1, NOW(), 10, NOW(),10),
	('Switches', 'Switches', 19, 5, 1, NOW(), 10, NOW(),10),
	('VOIP and Phone', 'VOIP and Phone', 19, 5, 1, NOW(), 10, NOW(),10),
	('Wireless Adapters', 'Wireless Adapters', 19, 5, 1, NOW(), 10, NOW(),10),
	('Case Accessories', 'Case Accessories', 20, 5, 1, NOW(), 10, NOW(),10),
	('Case Mod LED Lights', 'Case Mod LED Lights', 20, 5, 1, NOW(), 10, NOW(),10),
	('Computer Cases', 'Computer Cases', 20, 5, 1, NOW(), 10, NOW(),10),
	('CPUs / Processors', 'CPUs / Processors', 20, 5, 1, NOW(), 10, NOW(),10),
	('Fans & PC Cooling', 'Fans & PC Cooling', 20, 5, 1, NOW(), 10, NOW(),10),
	('Hard Drives', 'Hard Drives', 20, 5, 1, NOW(), 10, NOW(),10),
	('Memory', 'Memory', 20, 5, 1, NOW(), 10, NOW(),10),
	('Motherboards', 'Motherboards', 20, 5, 1, NOW(), 10, NOW(),10),
	('Power Supplies', 'Power Supplies', 20, 5, 1, NOW(), 10, NOW(),10),
	('Sound Cards', 'Sound Cards', 20, 5, 1, NOW(), 10, NOW(),10),
	('Video Cards', 'Video Cards', 20, 5, 1, NOW(), 10, NOW(),10),
	('Cooling Accessories', 'Cooling Accessories', 77, 5, 1, NOW(), 10, NOW(),10),
	('Cooling Fans', 'Cooling Fans', 77, 5, 1, NOW(), 10, NOW(),10),
	('CPU Cooling', 'CPU Cooling', 77, 5, 1, NOW(), 10, NOW(),10),
	('Liquid Cooling', 'Liquid Cooling', 77, 5, 1, NOW(), 10, NOW(),10),
	('Memory Cooling', 'Memory Cooling', 77, 5, 1, NOW(), 10, NOW(),10),
	('VGA Cooling', 'VGA Cooling', 77, 5, 1, NOW(), 10, NOW(),10),
	('Digital Performance Eyewear', 'Digital Performance Eyewear', 21, 5, 1, NOW(), 10, NOW(),10),
	('Display Accessories', 'Display Accessories', 21, 5, 1, NOW(), 10, NOW(),10),
	('Game Devices', 'Game Devices', 21, 5, 1, NOW(), 10, NOW(),10),
	('Headsets', 'Headsets', 21, 5, 1, NOW(), 10, NOW(),10),
	('Keyboard & Mouse Combo', 'Keyboard & Mouse Combo', 21, 5, 1, NOW(), 10, NOW(),10),
	('Keyboards', 'Keyboards', 21, 5, 1, NOW(), 10, NOW(),10),
	('KVM Accessories', 'KVM Accessories', 21, 5, 1, NOW(), 10, NOW(),10),
	('KVMs', 'KVMs', 21, 5, 1, NOW(), 10, NOW(),10),
	('Mices', 'Mices', 21, 5, 1, NOW(), 10, NOW(),10),
	('Mobile Projectors', 'Mobile Projectors', 21, 5, 1, NOW(), 10, NOW(),10),
	('Monitors', 'Monitors', 21, 5, 1, NOW(), 10, NOW(),10),
	('Mousepads', 'Mousepads', 21, 5, 1, NOW(), 10, NOW(),10),
	('Projectors', 'Projectors', 21, 5, 1, NOW(), 10, NOW(),10),
	('Speakers', 'Speakers', 21, 5, 1, NOW(), 10, NOW(),10),
	('TV Tuner & Capture', 'TV Tuner & Capture', 21, 5, 1, NOW(), 10, NOW(),10),
	('UPS', 'UPS', 21, 5, 1, NOW(), 10, NOW(),10),
	('Web Cams', 'Web Cams', 21, 5, 1, NOW(), 10, NOW(),10),
	('Color-Laser Printers', 'Color-Laser Printers', 22, 5, 1, NOW(), 10, NOW(),10),
	('Fax Machines', 'Fax Machines', 22, 5, 1, NOW(), 10, NOW(),10),
	('Ink Cartridges', 'Ink Cartridges', 22, 5, 1, NOW(), 10, NOW(),10),
	('Inkjet Multifunction Printers', 'Inkjet Multifunction Printers', 22, 5, 1, NOW(), 10, NOW(),10),
	('Inkjet Printers', 'Inkjet Printers', 22, 5, 1, NOW(), 10, NOW(),10),
	('Large Format Printers', 'Large Format Printers', 22, 5, 1, NOW(), 10, NOW(),10),
	('Mono-Laser Pinters', 'Mono-Laser Pinters', 22, 5, 1, NOW(), 10, NOW(),10),
	('Scanners', 'Scanners', 22, 5, 1, NOW(), 10, NOW(),10),
	('Toners (Compatible)', 'Toners (Compatible)', 22, 5, 1, NOW(), 10, NOW(),10),
	('Toners (Original)', 'Toners (Original)', 22, 5, 1, NOW(), 10, NOW(),10),
	('External Hard Drives', 'External Hard Drives', 23, 5, 1, NOW(), 10, NOW(),10),
	('Flash Memory / Memory Cards', 'Flash Memory / Memory Cards', 23, 5, 1, NOW(), 10, NOW(),10),
	('Hard Drive Docks', 'Hard Drive Docks', 23, 5, 1, NOW(), 10, NOW(),10),
	('Hard Drive Enclosures', 'Hard Drive Enclosures', 23, 5, 1, NOW(), 10, NOW(),10),
	('Internal Hard Drives', 'Internal Hard Drives', 23, 5, 1, NOW(), 10, NOW(),10),
	('Network Attached Storage (NAS)', 'Network Attached Storage (NAS)', 23, 5, 1, NOW(), 10, NOW(),10),
	('Optical Drives & Media', 'Optical Drives & Media', 23, 5, 1, NOW(), 10, NOW(),10),
	('SSDs', 'SSDs', 23, 5, 1, NOW(), 10, NOW(),10),
	('USB Flash Drives', 'USB Flash Drives', 23, 5, 1, NOW(), 10, NOW(),10),
	('External Optical Drives', 'External Optical Drives', 123, 5, 1, NOW(), 10, NOW(),10),
	('Internal Optical Drives', 'Internal Optical Drives', 123, 5, 1, NOW(), 10, NOW(),10),
	('Media', 'Media', 123, 5, 1, NOW(), 10, NOW(),10),
	('Barebones', 'Barebones', 6, 6, 1, NOW(), 10, NOW(),10),
	('Branded Computers', 'Branded Computers', 6, 6, 1, NOW(), 10, NOW(),10),
	('Branded Servers', 'Branded Servers', 6, 6, 1, NOW(), 10, NOW(),10),
	('Budget PC Custom Computers', 'Budget PC Custom Computers', 6, 6, 1, NOW(), 10, NOW(),10),
	('Budget PC Custom Servers', 'Budget PC Custom Servers', 6, 6, 1, NOW(), 10, NOW(),10),
	('FREE PC Assembly', 'FREE PC Assembly', 6, 6, 1, NOW(), 10, NOW(),10),
	('All-in-One PCs', 'All-in-One PCs', 130, 6, 1, NOW(), 10, NOW(),10),
	('Desktop Computers', 'Desktop Computers', 130, 6, 1, NOW(), 10, NOW(),10),
	('Workstations', 'Workstations', 130, 6, 1, NOW(), 10, NOW(),10),
	('Rack Servers', 'Rack Servers', 131, 6, 1, NOW(), 10, NOW(),10),
	('Tower Servers', 'Tower Servers', 131, 6, 1, NOW(), 10, NOW(),10),
	('Home & Business Range ', 'Home & Business Range ', 132, 6, 1, NOW(), 10, NOW(),10),
	('Performance Gaming Range', 'Performance Gaming Range', 132, 6, 1, NOW(), 10, NOW(),10),
	('Apple', 'Apple', 11, 11, 1, NOW(), 10, NOW(),10),
	('Mobile Phones', 'Mobile Phones', 11, 11, 1, NOW(), 10, NOW(),10),
	('Notebook Accessories', 'Notebook Accessories', 11, 11, 1, NOW(), 10, NOW(),10),
	('Notebooks / Ultrabooks', 'Notebooks / Ultrabooks', 11, 11, 1, NOW(), 10, NOW(),10),
	('Tablet Accessories', 'Tablet Accessories', 11, 11, 1, NOW(), 10, NOW(),10),
	('Tablets', 'Tablets', 11, 11, 1, NOW(), 10, NOW(),10),
	('iMac', 'iMac', 142, 11, 1, NOW(), 10, NOW(),10),
	('iPad', 'iPad', 142, 11, 1, NOW(), 10, NOW(),10),
	('iPhone', 'iPhone', 142, 11, 1, NOW(), 10, NOW(),10),
	('MacBook', 'MacBook', 142, 11, 1, NOW(), 10, NOW(),10),
	('Notebook Bags', 'Notebook Bags', 144, 11, 1, NOW(), 10, NOW(),10),
	('Notebook Batteries', 'Notebook Batteries', 144, 11, 1, NOW(), 10, NOW(),10),
	('Notebook Chargers/Adapters', 'Notebook Chargers/Adapters', 144, 11, 1, NOW(), 10, NOW(),10),
	('Notebook Cooling', 'Notebook Cooling', 144, 11, 1, NOW(), 10, NOW(),10),
	('Notebook Dockings', 'Notebook Dockings', 144, 11, 1, NOW(), 10, NOW(),10),
	('Notebook Locks', 'Notebook Locks', 144, 11, 1, NOW(), 10, NOW(),10),
	('Refurbished Accessories', 'Refurbished Accessories', 12, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Computers', 'Refurbished Computers', 12, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Monitors', 'Refurbished Monitors', 12, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Networking Products', 'Refurbished Networking Products', 12, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Notebooks', 'Refurbished Notebooks', 12, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Printers & Photocopiers', 'Refurbished Printers & Photocopiers', 12, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Server Parts', 'Refurbished Server Parts', 12, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Servers', 'Refurbished Servers', 12, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Storage Products', 'Refurbished Storage Products', 12, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Tablets', 'Refurbished Tablets', 12, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Thin Clients', 'Refurbished Thin Clients', 12, 12, 1, NOW(), 10, NOW(),10),
	('Refurbished Workstations', 'Refurbished Workstations', 12, 12, 1, NOW(), 10, NOW(),10),
	('Adobe', 'Adobe', 14, 14, 1, NOW(), 10, NOW(),10),
	('Anti Virus', 'Anti Virus', 14, 14, 1, NOW(), 10, NOW(),10),
	('Eletronic Software', 'Eletronic Software', 14, 14, 1, NOW(), 10, NOW(),10),
	('Licensing', 'Licensing', 14, 14, 1, NOW(), 10, NOW(),10),
	('Microsoft Office ', 'Microsoft Office ', 14, 14, 1, NOW(), 10, NOW(),10),
	('Microsoft Windows', 'Microsoft Windows', 14, 14, 1, NOW(), 10, NOW(),10),
	('Utilities', 'Utilities', 14, 14, 1, NOW(), 10, NOW(),10),
	('Surge Protector / Power Boards', 'Surge Protector / Power Boards', 21, 5, 1, NOW(), 10, NOW(),10);
update `productcategory` set position = rootId where id = rootId;
update `productcategory` set position = concat(rootId, '/', id) where parentId = rootId and id != rootId;
update `productcategory` set position = concat(rootId, '/', parentId, '/', id) where parentId != rootId and id != rootId;

CREATE TABLE `product_category` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `productId` int(10) unsigned NOT NULL DEFAULT '0',
  `categoryId` int(10) unsigned NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `productId` (`productId`),
  KEY `categoryId` (`categoryId`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE `product` DROP `price`, DROP INDEX `price`;



CREATE TABLE `productpricetype` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
insert into `productpricetype` (`id`, `name`, `description`, `active`, `created`, `createdById`, `updated`, `updatedById`) values
	(1, 'RRP', 'Recommended Retail Price / Normal sales price', 1, NOW(), 10, NOW(), 10),
	(2, 'Casual Special Price', 'Promotional purpose sepcial price', 1, NOW(), 10, NOW(), 10),
	(3, 'Special Price Group 1', 'Special Price For Group 1 Customers', 1, NOW(), 10, NOW(), 10),
	(4, 'Special Price Group 2', 'Special Price For Group 2 Customers', 1, NOW(), 10, NOW(), 10);
	
	
CREATE TABLE `productprice` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `productId` int(10) unsigned NOT NULL DEFAULT '0',
  `typeId` int(10) unsigned NOT NULL DEFAULT '0',
  `price` double(10,4) unsigned NOT NULL DEFAULT '0.0000',
  `start` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `end` datetime NOT NULL DEFAULT '9999-12-31 23:59:59',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `productId` (`productId`),
  KEY `typeId` (`typeId`),
  KEY `price` (`price`),
  KEY `start` (`start`),
  KEY `end` (`end`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `productstatus` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `createdById` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedById` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `created` (`created`),
  KEY `createdById` (`createdById`),
  KEY `updated` (`updated`),
  KEY `updatedById` (`updatedById`),
  KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

insert into `productstatus` (`id`, `name`, `description`, `active`, `created`, `createdById`, `updated`, `updatedById`) values
    (1, 'Back Order Only', 'Status for Any Back Order', 1, NOW(), 10, NOW(), 10),
    (2, 'In Stock', 'For products that we have stock', 1, NOW(), 10, NOW(), 10),
    (3, 'Pre Order', 'For produts that we have No stock', 1, NOW(), 10, NOW(), 10),
    (4, 'Ships in 24 Hrs', 'For produts that we have No stock but can ship in 24 hrs', 1, NOW(), 10, NOW(), 10),
    (5, 'Low Stock', 'For produts that low quantity on stock', 1, NOW(), 10, NOW(), 10);


ALTER TABLE `product` ADD `sellOnWeb` TINYINT( 1 ) NOT NULL DEFAULT '0' AFTER `isFromB2B`, add index (`sellOnWeb`);
ALTER TABLE `product` ADD `statusId` int(10) unsigned NOT NULL DEFAULT '0' AFTER `sellOnWeb`, add index (`statusId`);
ALTER TABLE `product` ADD `manufacturerId` int(10) unsigned NOT NULL DEFAULT '0' AFTER `statusId`, add index (`manufacturerId`);
ALTER TABLE `product` ADD `asNewFromDate` datetime NULL DEFAULT null AFTER `manufacturerId`, add index (`asNewFromDate`);
ALTER TABLE `product` ADD `asNewToDate` datetime NULL DEFAULT null AFTER `asNewFromDate`, add index (`asNewToDate`);
