var PageJs=new Class.create;
PageJs.prototype=Object.extend(new BPCPageJs,{_resultDivId:"",_searchDivId:"",_pagination:{pageNo:1,pageSize:30},_searchCriteria:{},_bindSearchKey:function(){var a;a=this;$(a._searchDivId).getElementsBySelector("[search_field]").each(function(c){c.observe("keydown",function(b){a.keydown(b,function(){$(a._searchDivId).down(".search_btn").click()})})});return this},init:function(a,c){this._resultDivId=a;this._searchDivId=c;this._bindSearchKey();return this},setSearchCriteria:function(a){var c;$(this._searchDivId).getElementsBySelector("[search_field]").each(function(b){c=
b.readAttribute("search_field");a[c]&&$(b).setValue(a[c])});return this},getSearchCriteria:function(){var a,c;a=this;a._searchCriteria={};c=!0;$(a._searchDivId).getElementsBySelector("[search_field]").each(function(b){a._searchCriteria[b.readAttribute("search_field")]=$F(b);if($F(b)instanceof Array&&0<$F(b).size()||"string"===typeof $F(b)&&!$F(b).blank())c=!1});!0===c&&(a._searchCriteria=null);return this},_getResultRow:function(a,c){var b,e,d,f;b=this;e=c||!1;return(new Element("tr",{"class":"item_row",
item_id:a.id})).store("data",a).insert({bottom:(new Element("td",{"class":"productname"})).update(a.product.name)}).insert({bottom:(new Element("td",{"class":"productsku"})).update(a.product.sku)}).insert({bottom:(new Element("td",{"class":"orderno"})).update(e?a.order.orderNo:(new Element("a",{href:"javascript: void(0);","class":"orderNolink"})).update(a.order.orderNo).observe("click",function(){jQuery.fancybox({width:"80%",height:"90%",autoScale:!0,type:"iframe",href:"/orderdetails/"+a.order.id+
".html",beforeClose:function(){$$("iframe.fancybox-iframe")&&$$("iframe.fancybox-iframe").first().contentWindow&&$$("iframe.fancybox-iframe").first().contentWindow.pageJs&&(d=$$("iframe.fancybox-iframe").first().contentWindow.pageJs._orderItems)&&0<d.size()&&d.each(function(c){(f=$(b._resultDivId).down(".row[item_id="+a.id+"]"))&&f.replace(b._getResultRow(c))})}})}))}).insert({bottom:(new Element("td",{"class":"orderstatus",order_status:a.order.status.name})).update(a.order.status.name)}).insert({bottom:(new Element("td",
{"class":"qty"})).update(a.qtyOrdered)}).insert({bottom:(new Element("td",{"class":"isordered"})).update(!0===c?a.isOrdered:a.isOrdered?new Element("span",{"class":"ticked inlineblock"}):"")}).insert({bottom:(new Element("td",{"class":"eta"})).update(a.eta)}).insert({bottom:(new Element("td",{"class":"comments"})).update(!0===c?"":(new Element("a",{href:"javascript: void(0);","class":"popovercomments visible-xs visible-sm visible-md visible-lg"})).update(new Element("span",{"class":"glyphicon glyphicon-comment"})).observe("click",
function(a){jQuery(".popovercomments").not(this).popover("hide")}))})},_getNextPageBtn:function(){var a;a=this;return(new Element("tr")).insert({bottom:(new Element("td",{colspan:"8","class":"text-center"})).insert({bottom:(new Element("span",{"class":"btn btn-success searching_btn","data-loading-text":"Getting more ..."})).update("Show More").observe("click",function(){a._pagination.pageNo=1*a._pagination.pageNo+1;a.getResults()})})})},_getCommentsDiv:function(a){var c;c="";a.comments.each(function(a){c+=
'<div class="list-group-item">';c+='<span class="badge">'+a.type+"</span>";c+='<strong class="list-group-item-heading"><small>'+a.createdBy.person.fullname+"</small></strong>: ";c+="<p><small><em> @ "+a.created+"</em></small><br /><small>"+a.comments+"</small></p>";c+="</div>"});return c},getResults:function(a,c){var b,e,d;b=this;null===b._searchCriteria||b._searchCriteria==={}?alert("Nothing to search!"):(!0===a&&($(b._resultDivId).update(""),$(b._resultDivId).up(".panel").down(".total_no_of_items").update("0")),
(e=$(b._resultDivId).down("table.table > tbody"))||$(b._resultDivId).update((new Element("table",{"class":"table"})).update(e=new Element("tbody"))),b.postAjax(b.getCallbackId("getOrderitems"),{searchCriteria:b._searchCriteria,pagination:b._pagination},{onCreate:function(a,b){jQuery(".searching_btn").button("loading")},onSuccess:function(c,g){try{(d=b.getResp(g,!1,!0))&&d.items&&(e.getElementsBySelector(".paginWrapper").each(function(a){a.remove()}),!0===a&&(e.insert({before:b._getResultRow({order:{orderNo:"Order NO.",
status:{name:"Order Status"}},product:{sku:"SKU",name:"Product"},qtyOrdered:"QTY",eta:"ETA",isOrdered:"Ordered?"},!0).wrap(new Element("thead"))}),$(b._resultDivId).up(".panel").down(".total_no_of_items").update(d.pageStats.totalRows)),d.items.each(function(a){e.insert({bottom:b._getResultRow(a)});jQuery(".popovercomments",jQuery(".item_row[item_id="+a.id+"]")).popover({container:"body",content:b._getCommentsDiv(a),html:!0,placement:"left",title:"Comments:",template:'<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content list-group"></div></div>'})}),
d.pageStats.pageNumber<d.pageStats.totalPages&&e.insert({bottom:b._getNextPageBtn().addClassName("paginWrapper")}))}catch(h){$(b._resultDivId).insert({bottom:b.getAlertBox("ERROR: ",h).addClassName("alert-danger").wrap(new Element("div",{"class":"panel-body"}))})}},onComplete:function(a,b){jQuery(".searching_btn").button("reset")}}))}});