var CommentsDivJs=new Class.create;
CommentsDivJs.prototype={SAVE_BTN_ID:"",_pageJs:null,initialize:function(a,b,d,c,f){this._pageJs=a;this._entityName=b;this._entityId=d;this._displayDivId=f;this._pageSize=c||5},_setDisplayDivId:function(a){this._displayDivId=a;return this},_getCommentsRow:function(a){var b;b=a.id?"td":"th";return(new Element("tr",{"class":"comments_row"})).store("data",a).insert({bottom:(new Element(b,{"class":"col-xs-1"})).update(a.id?(new Element("small")).update(this._pageJs.loadUTCTime(a.created).toLocaleString()):a.created)}).insert({bottom:(new Element(b,
{"class":"col-xs-1"})).update(a.id?(new Element("small")).update(a.createdBy.person.fullname):a.createdBy.person.fullname)}).insert({bottom:(new Element(b,{"class":"col-xs-1"})).update(a.id?(new Element("small")).update(a.type):a.type)}).insert({bottom:(new Element(b,{"class":""})).update(a.id?(new Element("small")).update(a.comments):a.comments)})},_getComments:function(a,b,d){var c,f,g,e,k,h;c=this;f=a||1;g=c._pageJs.getLoadingImg();e=d?$(d):void 0;new Ajax.Request("/ajax/getComments",{method:"get",
parameters:{entity:c._entityName,entityId:c._entityId,orderBy:{created:"desc"},pageNo:a,pageSize:c._pageSize},onCreate:function(){1===f&&$(b).update(g);e&&(c._pageJs._signRandID(e),jQuery("#"+e.id).button("loading"))},onSuccess:function(d){try{1===f?$(b).update(""):$(b).down(".comments_get_more_btn_div")&&$(b).down(".comments_get_more_btn_div").remove(),(k=$(b).down("tbody"))||$(b).insert({bottom:(new Element("table",{"class":"table table-condensed table-hover"})).insert({bottom:(new Element("thead")).update(c._getCommentsRow({type:"Type",
createdBy:{person:{fullname:"WHO"}},created:"WHEN",comments:"COMMENTS"}))}).insert({bottom:k=new Element("tbody")})}),(h=c._pageJs.getResp(d.responseText,!1,!0))&&h.items&&(h.items.each(function(a){k.insert({bottom:c._getCommentsRow(a)})}),h.pageStats.pageNumber<h.pageStats.totalPages&&k.insert({bottom:(new Element("tr",{"class":"comments_get_more_btn_div"})).insert({bottom:(new Element("td",{colspan:4})).insert({bottom:(new Element("span",{"class":"btn btn-primary btn-xs","data-loading-text":"Getting More ..."})).update("Get More Comments").observe("click",
function(){c._getComments(1*a+1,b,this)})})})}))}catch(e){1===f?$(b).insert({bottom:c.getAlertBox("ERROR: ",e).addClassName("alert-danger")}):c._pageJs.showModalBox('<strong class="text-danger">Error</strong>',e)}},onComplete:function(){g.remove();e&&jQuery("#"+e.id).button("reset")}});return this},_addComments:function(a,b){var d,c,f,g,e;d=this;c=$(a).up(".new_comments_wrapper").down("[new_comments=comments]");f=$F(c);if(f.blank())return this;d._pageJs.postAjax(CommentsDivJs.SAVE_BTN_ID,{comments:f,
entityId:d._entityId,entityName:d._entityName},{onCreate:function(b,c){jQuery("#"+a.id).button("loading")},onSuccess:function(a,f){try{(g=d._pageJs.getResp(f,!1,!0))&&g.item&&g.item.id&&((e=$(b).down("tbody"))||$(b).insert({bottom:e=new Element("tbody")}),e.insert({top:d._getCommentsRow(g.item)}),c.setValue(""))}catch(l){d._pageJs.showModalBox('<strong class="text-danger">Error</strong>',l)}},onComplete:function(){jQuery("#"+a.id).button("reset")}});return this},_getEmptyCommentsDiv:function(a){var b;
b=this;return(new Element("div",{"class":"row new_comments_wrapper"})).insert({bottom:(new Element("div",{"class":"col-xs-2 text-right"})).update("<strong>New Comments:</strong>")}).insert({bottom:(new Element("div",{"class":"col-xs-10"})).insert({bottom:(new Element("div",{"class":"input-group"})).insert({bottom:(new Element("input",{"class":"form-control",type:"text",new_comments:"comments",placeholder:"add more comments to this order"})).observe("keydown",function(a){b._pageJs.keydown(a,function(){$(a.currentTarget).up(".new_comments_wrapper").down("[new_comments=btn]").click()})})}).insert({bottom:(new Element("span",
{"class":"input-group-btn"})).insert({bottom:(new Element("span",{id:"add_new_comments_btn",new_comments:"btn","class":"btn btn-primary","data-loading-text":"saving..."})).update("add").observe("click",function(){b._addComments(this,a)})})})})})},render:function(){var a,b;a=(new Element("div",{"class":"panel panel-default"})).insert({bottom:(new Element("div",{"class":"panel-heading"})).update("Comments:")}).insert({bottom:b=new Element("div",{"class":"comments_result_list table-responsive"})}).insert({bottom:(new Element("div",
{"class":"panel-footer"})).update(this._getEmptyCommentsDiv(b))});$(this._displayDivId).update(a);this._getComments(1,b)}};