var PageJs=new Class.create;
PageJs.prototype=Object.extend(new BPCPageJs,{resultDivId:"",searchDivId:"",totalNoOfItemsId:"",_pagination:{pageNo:1,pageSize:10},_searchCriteria:{},_infoTypes:{},orderStatuses:[],_type:"INVOICE",_loadChosen:function(){jQuery(".chosen").select2();return this},_bindSearchKey:function(){var a;a=this;$("searchDiv").getElementsBySelector("[search_field]").each(function(c){c.observe("keydown",function(b){a.keydown(b,function(){$("searchBtn").click()})})});return this},_loadStatuses:function(a){this.orderStatuses=a;
var c;c=$(this.searchDivId).down("#orderStatusId");this.orderStatuses.each(function(a){c.insert({bottom:(new Element("option",{value:a.id})).update(a.name)})});return this},setSearchCriteria:function(a){var c,b,e,d,f,g;c=$(this.searchDivId);$H(a).each(function(a){b=a.key;e=a.value;if(d=c.down('[search_field="'+b+'"]'))for(f=d.options.length,g=0;g<f;g++)0<=e.indexOf(1*d.options[g].value)&&(d.options[g].selected=!0)});this._loadChosen()._bindSearchKey();return this},getSearchCriteria:function(){var a,
c,b,e;a=this;null===a._searchCriteria&&(a._searchCriteria={});c=!0;$(a.searchDivId).getElementsBySelector("[search_field]").each(function(d){b=d.readAttribute("search_field");d.hasClassName("datepicker")?(a._signRandID(d),e=jQuery("#"+d.id).data("DateTimePicker").date(),a._searchCriteria[b]=e?new Date(e.local().format("YYYY-MM-DDT"+("orderDate_from"===b||"invDate_from"===b?"00:00:00":"23:59:59"))):""):a._searchCriteria[b]=$F(d);if($F(d)instanceof Array&&0<$F(d).size()||"string"===typeof $F(d)&&!$F(d).blank())c=
!1});!0===c&&(a._searchCriteria=null);return this},getResults:function(a,c){var b,e,d,f,g,h,k;b=this;e=a||!1;null===b._searchCriteria?b.showModalBox("Warning","Nothing to search!",!0):(!0===e&&(b._pagination.pageNo=1),b._pagination.pageSize=c||b._pagination.pageSize,b._searchCriteria["ord.type"]=b._type,b._searchCriteria.extraSearchCriteria=b._extraSearchCriteria?b._extraSearchCriteria:"",b.postAjax(b.getCallbackId("getOrders"),{pagination:b._pagination,searchCriteria:b._searchCriteria},{onLoading:function(){jQuery("#searchBtn").button("loading");
jQuery(".popovershipping").popover("hide");!0===e&&($(b.totalNoOfItemsId).update("0"),$(b.totalSumId).update(b.getCurrency(0)),$(b.totalDueId).update(b.getCurrency(0)),$(b.resultDivId).update("").insert({after:(new Element("div",{"class":"panel-body"})).update(b.getLoadingImg())}))},onSuccess:function(a,c){try{if(d=b.getResp(c,!1,!0))$(b.totalNoOfItemsId).update(d.pageStats.totalRows),$(b.totalSumId).update(b.getCurrency(d.totalAmount)),$(b.totalDueId).update((new Element("span",{title:"Total Amt: "+
b.getCurrency(d.totalAmount)+"\nTotal Paid: "+b.getCurrency(d.totalPaid)+"\nTotal Credited: "+b.getCurrency(d.totalCreditNoteValue)+"\nTotal PaidViaCrdit: "+b.getCurrency(d.paidViaCredit)})).update(b.getCurrency(d.totalAmount-d.totalPaid-d.totalCreditNoteValue+1*d.paidViaCredit))),f=$(b.resultDivId),!0===e&&(g={orderNo:"Order Info.",type:"Type",custName:"Customer Name",shippingAddr:"Shipping Address",invNo:"Invoice No.",status:{name:"Status"},totalDue:"Total Due",passPaymentCheck:"Payment Cleared?"},
f.update(b._getResultRow(g,!0).wrap(new Element("thead")))),f.getElementsBySelector(".paginWrapper").each(function(a){a.remove()}),(h=$(f).down("tbody"))||$(f).insert({bottom:h=new Element("tbody")}),d.items.each(function(a){h.insert({bottom:b._getResultRow(a)})}),d.pageStats.pageNumber<d.pageStats.totalPages&&f.insert({bottom:b._getNextPageBtn().addClassName("paginWrapper")}),f.getElementsBySelector(".popovershipping.newPopover").each(function(a){a.removeClassName("newPopover");k=a.up(".order_item").retrieve("data");
jQuery("#"+a.id).popover({container:"body",title:'<div class="row"><div class="col-xs-10">Details for: '+k.orderNo+'</div><div class="col-xs-2"><a class="pull-right" href="javascript:void(0);" onclick="jQuery(\'#'+a.id+"').popover('hide');\"><strong>&times;</strong></a></div></div>",content:jQuery(".popover_content",jQuery("#"+a.id)).html(),html:!0,placement:"right",trigger:"manual"})})}catch(l){b.showModalBox('<strong class="text-danger">Error</strong>',l,!0)}},onComplete:function(){jQuery("#searchBtn").button("reset");
$(b.resultDivId).up(".panel").down(".panel-body")&&$(b.resultDivId).up(".panel").down(".panel-body").remove()}}))},_getNextPageBtn:function(){var a;a=this;return(new Element("tfoot")).insert({bottom:(new Element("tr")).insert({bottom:(new Element("td",{colspan:"11","class":"text-center"})).insert({bottom:(new Element("span",{"class":"btn btn-primary","data-loading-text":"Fetching more results ..."})).update("Show More").observe("click",function(){a._pagination.pageNo=1*a._pagination.pageNo+1;jQuery(this).button("loading");
a.getResults()})})})})},_getOrderDetailsDiv:function(a){var c,b;c=a.infos[this._infoTypes.custName][0].value;b=a.infos[this._infoTypes.custEmail][0].value;return(new Element("div")).insert({bottom:(new Element("div")).update('<span class="glyphicon glyphicon-user" title="Customer Name"></span>: '+c)}).insert({bottom:(new Element("div")).update('<span class="glyphicon glyphicon-envelope" title="Customer Email"></span>: <a href="mailto:'+b+'">'+b+"</a>")}).insert({bottom:(new Element("div")).update('<span class="glyphicon glyphicon-shopping-cart" title="Order Date"></span>: '+
a.orderDate)}).insert({bottom:(new Element("div")).update("<strong>Shipping</strong>:")}).insert({bottom:(new Element("div")).update('<span class="glyphicon glyphicon-user" title="Customer Name"></span>: '+a.address.shipping.contactName)}).insert({bottom:(new Element("div")).update('<span class="glyphicon glyphicon-phone-alt" title="Phone"></span>: '+a.address.shipping.contactNo)}).insert({bottom:(new Element("div")).update('<span class="glyphicon glyphicon-map-marker" title="Address"></span>: '+
a.address.shipping.full)})},_getTitledDiv:function(a,c){return(new Element("div",{"class":"field_div"})).insert({bottom:(new Element("span",{"class":"inlineblock title"})).update(a)}).insert({bottom:(new Element("span",{"class":"inlineblock divcontent"})).update(c)})},_openDetailsPage:function(a){var c;c=this;jQuery.fancybox({width:"95%",height:"95%",autoScale:!1,autoDimensions:!1,fitToView:!1,autoSize:!1,helpers:{overlay:{locked:!1}},type:"iframe",href:"/orderdetails/"+a.id+".html?blanklayout=1",
beforeClose:function(){a&&a.id&&$(c.resultDivId).down(".order_item[order_id="+a.id+"]")&&$$("iframe.fancybox-iframe").first().contentWindow.pageJs&&$$("iframe.fancybox-iframe").first().contentWindow.pageJs._order&&$(c.resultDivId).down(".order_item[order_id="+a.id+"]").replace(c._getResultRow($$("iframe.fancybox-iframe").first().contentWindow.pageJs._order))}});return c},_getOrderInfoCell:function(a){var c,b,e,d;c=this;b=(new Element("div")).insert({bottom:(new Element("span")).insert({bottom:e=(new Element("a",
{id:"orderno-btn-"+a.id,"class":"orderNo visible-xs visible-sm visible-md visible-lg newPopover popovershipping",href:"javascript:void(0);"})).update(a.orderNo).insert({bottom:(new Element("div",{style:"display: none;","class":"popover_content"})).update(c._getOrderDetailsDiv(a))})})});c.observeClickNDbClick(e,function(b){d=b.target;jQuery(d).popover("hide");c._openDetailsPage(a)},function(a){});return b},_getPaymentCell:function(a,c){var b,e,d,f;b=this;switch(c){case "totalAmount":e="Total Amout";
d="totalAmount";break;case "totalPaid":e="Total Paid";d="totalPaid";break;case "totalCreditNoteValue":e="Total Credit Note Value";d="totalCreditNoteValue";break;default:e="ERROR(_getPaymentCell)"}return(new Element("a",{href:"javascript: void(0);"})).insert({bottom:a.passPaymentCheck&&"totalPaid"===c?(new Element("span",{title:0>=Math.round(a.totalDue,2)?"Full Paid":"Short Paid","class":0>=Math.round(a.totalDue,2)?"text-success":"text-danger"})).setStyle("margin-right: 3px;").update(new Element("span",
{"class":"glyphicon "+(0>=Math.round(a.totalDue,2)?"glyphicon-ok-sign":"glyphicon-warning-sign")})):""}).insert({bottom:(new Element("span")).update(f=b.getCurrency(a[d])).writeAttribute("title",e+":"+f)}).observe("click",function(){"totalCreditNoteValue"===d?window.open("/creditnote.html?orderid="+a.id,"_blank"):b._openDetailsPage(a)})},_getMarginCell:function(a){var c;c=this;return(new Element("a",{href:"javascript: void(0);"})).insert({bottom:(new Element("span")).update(c.getCurrency(a.margin)).writeAttribute("title",
"Order margin:"+c.getCurrency(a.margin))}).observe("click",function(){c._openDetailsPage(a)})},_getPurchasingCell:function(a){var c,b,e;c=this;b=0<=["4","5","6","7","8"].indexOf(a.status.id);e=0<=["4","6"].indexOf(a.status.id);return(new Element("div")).insert({bottom:b?(new Element("a",{href:"javascript: void(0);","class":e?"text-danger":"text-success",title:a.stockChkedWIssues?"insufficient stock":"Stock checked"})).update(new Element("span",{"class":"glyphicon "+(e?"glyphicon-warning-sign":"glyphicon-ok-sign")})).observe("click",
function(){c._openDetailsPage(a)}):""})},_getWarehouseCell:function(a){var c,b,e;c=this;b=0<=["6","7","8"].indexOf(a.status.id);e=0<=["6"].indexOf(a.status.id);return(new Element("div")).insert({bottom:b?(new Element("a",{href:"javascript: void(0);","class":e?"text-danger":"text-success",title:a.chkedWIssues?"insufficient stock":"Stock Handled successfully"})).update(new Element("span",{"class":"glyphicon "+(e?"glyphicon-warning-sign":"glyphicon-ok-sign")})).observe("click",function(){c._openDetailsPage(a)}):
""})},_getResultRow:function(a,c){var b,e,d,f,g;b=this;d=(e=c||!1)?"D.Method":a.infos["9"]?a.infos[9][0].value:"";f=(new Element("tr",{"class":!0===e?"":"order_item",order_id:a.id})).store("data",a).insert({bottom:(new Element("td",{"class":"orderInfo  col-xs-1"})).update(e?"Order No.":b._getOrderInfoCell(a))}).insert({bottom:(new Element("td",{"class":"order-date col-xs-1"})).update(!0===e?"Order Date":moment(b.loadUTCTime(a.orderDate)).format("ll"))}).insert({bottom:(new Element("td",{"class":"invoiceNo col-xs-1"})).update(!0===
e?"Inv. No.":(new Element("small")).update(a.invNo))}).insert({bottom:(new Element("td",{"class":"customer"})).update(!0===e?"Customer":a.customer.name)}).insert({bottom:(new Element("td",{"class":"col-xs-3"})).update((new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"text-right col-xs-3 "})).update(e?"Total Amt":b._getPaymentCell(a,"totalAmount"))}).insert({bottom:(new Element("div",{"class":"text-right col-xs-4 "})).update(e?"Paid Amt":b._getPaymentCell(a,"totalPaid"))}).insert({bottom:(new Element("div",
{"class":"col-xs-2 "+(0<a.totalCreditNoteValue?"tr-red":"")})).setStyle("padding: 0px;").update(e?"Credit Amt":b._getPaymentCell(a,"totalCreditNoteValue"))}).insert({bottom:(new Element("div",{"class":"text-right col-xs-3 "})).update(e?"Margin":b._getMarginCell(a))}))}).insert({bottom:(new Element("td",{"class":"col-xs-1"})).update((new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-xs-6 text-center",title:"Purchasing"})).update(e?"Pur.":b._getPurchasingCell(a))}).insert({bottom:(new Element("div",
{"class":"col-xs-6 text-center",title:"Warehouse"})).update(e?"Ware.":b._getWarehouseCell(a))}))}).insert({bottom:(new Element("td",{"class":"status col-xs-1 truncate",title:a.status.name,order_status:a.status.name})).update(a.status?a.status.name:"")}).insert({bottom:g=(new Element("td",{"class":"col-xs-1 truncate"+(-1<d.toLowerCase().indexOf("pickup")?" danger":""),title:d})).update(d)});b.observeClickNDbClick(g,function(){},e?function(){}:function(){b.showModalBox("Delivery Method for Order "+
a.orderNo,d)});return f},_initDeliveryMethods:function(){var a,c;a=$(this.searchDivId).down('[search_field="delivery_method"]');this._signRandID(a);jQuery("#"+a.id).select2({minimumInputLength:3,multiple:!0,ajax:{delay:250,url:"/ajax/getDeliveryMethods",type:"POST",data:function(a){return{searchTxt:a}},results:function(a,e,d){c=[];a.resultData&&a.resultData.items&&a.resultData.items.each(function(a){c.push({id:a+"{|}",text:a.stripTags()})});return{results:c}},cache:!0}});return this},_initCustomerSelect2:function(){var a,
c;a=$(this.searchDivId).down("#custName");this._signRandID(a);jQuery("#"+a.id).select2({minimumInputLength:3,multiple:!1,allowClear:!0,ajax:{delay:250,url:"/ajax/getCustomers",type:"POST",data:function(a){return{searchTxt:a}},results:function(a,e,d){c=[];a.resultData&&a.resultData.items&&a.resultData.items.each(function(a){c.push({id:a.name,text:a.name,data:a})});return{results:c}},cache:!0}});return this},_changeType:function(a){var c;jQuery(".type-swither-item.active").removeClass("active");this._type=
$(a).addClassName("active").readAttribute("data-type");this._extraSearchCriteria=$(a).readAttribute("extraSearchCriteria");c="panel-default";switch(this._type){case "ORDER":c="panel-success";break;case "INVOICE":c="panel-default";break;case "QUOTE":c="panel-warning"}$(a).up(".panel").removeClassName("panel-success").removeClassName("panel-default").removeClassName("panel-warning").addClassName(c);$("searchBtn").click();return this},_initTypeSwither:function(){var a;a=this;$$(".type-swither-item").each(function(c){c.observe("click",
function(){a._changeType(this)})});return a},init:function(){var a;jQuery(".datepicker").datetimepicker({format:"DD/MM/YYYY"});this._initDeliveryMethods()._initCustomerSelect2()._initTypeSwither();$("right-panel").store("InsufficientStockOrdersListPanelJs",a=new InsufficientStockOrdersListPanelJs(this)).update(a.getListPanel().addClassName("panel-default"));a.load();return this}});