var PageJs=new Class.create;
PageJs.prototype=Object.extend(new BPCPageJs,{id_wrapper:"",_acceptableTypes:["csv"],csvFileLineFormat:["sku","price"],_fileReader:null,_uploadedData:{},_html_ids:{uploadedFileList:"uploaded_file_list",uploadInputDiv:"upload_input_div",resultListDiv:"result_list_div"},_companyAliases:{},load:function(b,a){this.id_wrapper=b;this._companyAliases=a;window.File&&window.FileReader&&window.FileList&&window.Blob?(this._fileReader=new FileReader,$(this.id_wrapper).update(this._getFileUploadDiv())):$(this.id_wrapper).update(this.getAlertBox("Warning:",
"Your browser does NOT support this feature. pls change and try again").addClassName("alert-warning"));return this},_genTemplate:function(){var b,a;b=[];b.push(this.csvFileLineFormat.join(", ")+"\n");a=new Date;a="pricematch_template_"+a.getFullYear()+"_"+a.getMonth()+"_"+a.getDate()+"_"+a.getHours()+"_"+a.getMinutes()+"_"+a.getSeconds()+".csv";b=new Blob(b,{type:"text/csv;charset=utf-8"});saveAs(b,a);return this},_getFileUploadDiv:function(){var b,a;b=this;return(new Element("div",{"class":"panel panel-default drop_file_div",
title:"You can drag multiple files here!"})).insert({bottom:(new Element("div",{"class":"panel-body"})).insert({bottom:(new Element("div",{"class":"btn-group pull-right"})).insert({bottom:(new Element("span",{"class":"btn btn-default",title:"Edit Companies"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-cog"})}).observe("click",function(){jQuery.fancybox({width:"90%",height:"90%",autoScale:!1,autoDimensions:!1,fitToView:!1,autoSize:!1,type:"iframe",href:"/pricematchcompanies.html",
beforeClose:function(){window.location=document.URL}})})}).insert({bottom:(new Element("span",{"class":"btn btn-default",title:"Download Template"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-download-alt"})}).observe("click",function(){b._genTemplate()})})}).insert({bottom:(new Element("div",{"class":"form-group center-block text-left",style:"width: 50%"})).insert({bottom:(new Element("label")).update("Drop you files here or select your file below:")}).insert({bottom:a=(new Element("input",
{type:"file",style:"display: none;",multiple:!0})).observe("change",function(a){b._readFiles(a.target.files)})}).insert({bottom:new Element("div",{"class":"clearfix"})}).insert({bottom:(new Element("span",{"class":"btn btn-success clearfix"})).update("Click to select your file").observe("click",function(b){a.click()})}).insert({bottom:new Element("div",{"class":"clearfix"})}).insert({bottom:(new Element("small")).update("ONLY ACCEPT file formats: "+b._acceptableTypes.join(", "))})})}).observe("dragover",
function(a){a.stopPropagation();a.preventDefault();a.dataTransfer.dropEffect="copy"}).observe("drop",function(a){a.stopPropagation();a.preventDefault();b._readFiles(a.dataTransfer.files)})},_readFiles:function(b){var a,g,c,d,f,e,k,h,m,l;a=this;a._uploadedData={};g=new Element("div",{"class":"list-group"});for(c=0;c<b.length;c++)d=b[c],f=(new Element("div",{"class":"row"})).update((new Element("div",{"class":"col-lg-6 col-md-6"})).update(d.name)),""!==(e=d.name.split(".").pop())&&-1<a._acceptableTypes.indexOf(e.toLowerCase())?
(a._fileReader=new FileReader,a._fileReader.onload=function(b){b.target.result.split(/\r\n|\n|\r/).each(function(b){if(null!==b&&!b.blank()&&(k=[],b.split(",").each(function(a){null===a||a.blank()||k.push(a.strip())}),h=k.join(","),h!==a.csvFileLineFormat.join(","))){m={};for(l=0;l<a.csvFileLineFormat.size();l++)m[a.csvFileLineFormat[l]]=k[l];a._uploadedData[h]=m}})},a._fileReader.readAsText(d),d=!0):(f.insert({bottom:(new Element("div",{"class":"col-lg-6 col-md-6"})).update((new Element("small")).update("Not supported file extension: "+
e))}),d=!1),g.insert({bottom:(new Element("div",{"class":"list-group-item "+(!0===d?"list-group-item-success":"list-group-item-danger")})).insert({bottom:f})});$(a.id_wrapper).update((new Element("div",{"class":"panel panel-default"})).insert({bottom:(new Element("div",{"class":"panel-heading"})).update("Files Selected:").insert({bottom:(new Element("small",{"class":"pull-right"})).update("ONLY ACCEPT file formats: "+a._acceptableTypes.join(", "))})}).insert({bottom:g}).insert({bottom:(new Element("div",
{"class":"panel-footer"})).insert({bottom:(new Element("span",{"class":"btn btn-success"})).update("Start").observe("click",function(){a._loadProductLineItems()})}).insert({bottom:(new Element("span",{"class":"btn btn-warning pull-right"})).update("Cancel").observe("click",function(){$(a.id_wrapper).update(a._getFileUploadDiv())})})}));return a},genCSV:function(b){var a,g,c,d,f,e;a=this;g=[];c="SKU, My Price, Price Diff., Min. Price";$H(a._companyAliases).each(function(a){c=c+", "+a.key});g.push(c+
"\n");$(b).up(".panel").getElementsBySelector(".result_row.result-done").each(function(b){d=b.retrieve("data");f=d.sku+", "+d.myPrice+", "+d.minPrice+", "+d.priceDiff;$H(a._companyAliases).each(function(b){f=f+", "+a.getCurrency(d.companyPrices[b.key].price,"$",2,".","")});f+="\n";g.push(f)});b=new Date;b="pricematch_"+b.getFullYear()+"_"+b.getMonth()+"_"+b.getDate()+"_"+b.getHours()+"_"+b.getMinutes()+"_"+b.getSeconds()+".csv";e=new Blob(g,{type:"text/csv;charset=utf-8"});saveAs(e,b);return a},_getProductLineItem:function(b,
a,g){var c,d,f,e,k,h;c=this;d=c._uploadedData[g[a]];f=(new Element("tr",{"class":"result_row info"})).insert({bottom:(new Element("td")).update(d.sku)}).insert({bottom:(new Element("td")).update(c.getCurrency(d.price))}).insert({bottom:(new Element("td",{colspan:2})).update("<strong>Loading...</strong>")});c.postAjax(c.getCallbackId("getAllPricesForProduct"),{sku:d.sku,price:d.price,companyAliases:c._companyAliases},{onCreate:function(a,c){b.insert({bottom:f})},onSuccess:function(a,b){try{(e=c.getResp(b,
!1,!0))&&e.item&&(f.update("").removeClassName("info").addClassName("result-done").store("data",e.item).insert({bottom:(new Element("td")).update(e.item.sku)}).insert({bottom:(new Element("td")).update(c.getCurrency(e.item.myPrice))}).insert({bottom:(new Element("td",{"class":"price_diff"+(0<e.item.priceDiff?" over_priced":"")})).update(c.getCurrency(e.item.priceDiff))}).insert({bottom:(new Element("td",{"class":"price_min",title:"Min. Price among all Companies"})).update(c.getCurrency(e.item.minPrice))}),
$H(c._companyAliases).each(function(a){f.insert({bottom:(new Element("td")).update(e.item.companyPrices[a.key].priceURL.blank()?(new Element("span",{title:'No value has been found for "'+a.key+'" based on sku: '+d.sku})).update(c.getCurrency(e.item.companyPrices[a.key].price)):(new Element("a",{href:e.item.companyPrices[a.key].priceURL})).update(c.getCurrency(e.item.companyPrices[a.key].price)))})}))}catch(g){f.update("").removeClassName("info").addClassName("danger").store("data",d).insert({bottom:(new Element("td")).update(d.sku)}).insert({bottom:(new Element("td")).update(c.getCurrency(d.price))}).insert({bottom:(new Element("td",
{colspan:2})).update("<strong>ERROR:</strong>"+g)})}},onComplete:function(d,e){try{k=1*a+1,k>=g.size()?(h=$(c.id_wrapper).getElementsBySelector(".result_row.danger"),b.up(".panel").removeClassName("panel-danger").addClassName(0<h.size()?"panel-warning":"panel-success").down(".panel-heading").update("").insert({bottom:(new Element("panel-title")).update(0<h.size()?"All provided rows have been proccessed, but with "+h.size()+" error(s)":"All provided rows have been proccessed successfully")}).insert({bottom:(new Element("span",
{"class":"btn-group btn-group-sm pull-right"})).insert({bottom:(new Element("span",{"class":"btn"})).writeAttribute("title",0<h.size()?"Export Success Rows":"Export To Excel").update(new Element("span",{"class":"glyphicon glyphicon-save"})).addClassName(0<h.size()?"btn-warning":"btn-success").observe("click",function(){c.genCSV(this)})}).insert({bottom:(new Element("span",{"class":"btn btn-default"})).writeAttribute("title","Start Again").update(new Element("span",{"class":"glyphicon glyphicon-repeat"})).observe("click",
function(){window.location=document.URL})})})):c._getProductLineItem(b,k,g)}catch(f){alert(f)}}});return c},_loadProductLineItems:function(){var b,a,g;b=[];$H(this._uploadedData).each(function(a){b.push(a.key)});a=(new Element("tr")).insert({bottom:(new Element("th")).update("SKU")}).insert({bottom:(new Element("th")).update("My Price")}).insert({bottom:(new Element("th",{"class":"price_diff"})).update("Price Diff.")}).insert({bottom:(new Element("th",{"class":"price_min"})).update("Min Price")});
$H(this._companyAliases).each(function(b){a.insert({bottom:(new Element("th")).update(b.key)})});$(this.id_wrapper).update((new Element("div",{"class":"price_search_result panel panel-danger table-responsive"})).insert({bottom:(new Element("div",{"class":"panel-heading"})).update("Total of <strong>"+b.size()+"</strong> unique row(s) received:").insert({bottom:(new Element("strong",{"class":"pull-right"})).update("please waiting for it to finish")})}).insert({bottom:(new Element("table",{"class":"table table-striped"})).insert({bottom:(new Element("thead")).update(a)}).insert({bottom:g=
new Element("tbody")})}));this._getProductLineItem(g,0,b);return this}});