var PageJs=new Class.create;
PageJs.prototype=Object.extend(new CRUDPageJs,{_getTitleRowData:function(){return{status:"Status",applyTo:"Apply To",raNo:"RMA No",description:"Description",totalValue:"Total Value",active:"Active",customer:{name:"Name"},order:{orderNo:"Order No"}}},_bindSearchKey:function(){var a,c,b;a=this;$$("#searchBtn").first().observe("click",function(b){$$("#showSearch").first().checked?a.getSearchCriteria().getResults(!0,a._pagination.pageSize):$$("#showSearch").first().click()});$("searchDiv").getElementsBySelector("[search_field]").each(function(b){b.observe("keydown",
function(b){a.keydown(b,function(){$(a.searchDivId).down("#searchBtn").click()})})});c=(new Element("input",{"class":"select2 form-control","data-placeholder":"search for a Customers",search_field:"cust.id"})).insert({bottom:(new Element("option")).update("")});$("searchDiv").down('[search_field="cust.id"]').replace(c);jQuery('.select2[search_field="cust.id"]').select2({allowClear:!0,hidden:!0,multiple:!0,ajax:{url:"/ajax/getCustomers",dataType:"json",delay:10,data:function(a){return{searchTxt:a}},
results:function(a){b=[];a.resultData.items.each(function(a){b.push({id:a.id,text:a.name,data:a})});return{results:b}},cache:!0},formatResult:function(a){return a?"<div value="+a.data.id+">"+a.data.name+"</div >":""},escapeMarkup:function(a){return a},minimumInputLength:1});c=(new Element("input",{"class":"select2 form-control","data-placeholder":"search for a Products",search_field:"pro.ids"})).insert({bottom:(new Element("option")).update("")});$("searchDiv").down('[search_field="pro.ids"]').replace(c);
jQuery('.select2[search_field="pro.ids"]').select2({allowClear:!0,hidden:!0,multiple:!0,ajax:{url:"/ajax/getProducts",dataType:"json",delay:10,data:function(a){return{searchTxt:a,pageNo:1,pageSize:10}},results:function(a){b=[];a.resultData.items.each(function(a){b.push({id:a.id,text:a.name,data:a})});return{results:b}},cache:!0},formatResult:function(a){return a?"<div value="+a.data.id+">"+a.data.name+"</div >":""},escapeMarkup:function(a){return a},minimumInputLength:3});c=(new Element("select",
{"class":"select2 form-control","data-placeholder":"search for a Status",search_field:"ra.status",multiple:!0})).insert({bottom:(new Element("option")).update("")});a._statusOptions.each(function(a){c.insert({bottom:(new Element("option",{value:a})).update(a)})});$("searchDiv").down('[search_field="ra.status"]').replace(c);jQuery('.select2[search_field="ra.status"]').select2({allowClear:!0});return this},_openEditPage:function(a){var c,b,d;c=this;jQuery.fancybox({width:"95%",height:"95%",autoScale:!1,
autoDimensions:!1,fitToView:!1,autoSize:!1,type:"iframe",frameborder:"0",border:"0",seamless:"seamless",href:"/rma/"+(a&&a.id?a.id:"new")+".html",beforeClose:function(){d=(b=$$("iframe.fancybox-iframe").first().contentWindow.pageJs)&&b._RMA&&b._RMA.id?c._getResultRow(b._RMA):null;null!==d&&(a&&a.id?$(c.resultDivId).down(".item_row[item_id="+a.id+"]")&&$(c.resultDivId).down(".item_row[item_id="+a.id+"]").replace(d):$(c.resultDivId).insert({top:d}))}});return c},_highlightSelectedRow:function(a){a=
a.down(".glyphicon-plus")?"":$(a).up("[item_id]").retrieve("data");jQuery(".item_row.success").removeClass("success");jQuery("[item_id="+a.id+"]").addClass("success")},_displaySelectedAddress:function(a){var c,b;c=$(a).up("[item_id]").retrieve("data");b=$(a).down("span").classList.contains("address-shipping");jQuery(".popover-loaded").popover("hide");jQuery(".item_row.success").removeClass("success");jQuery("[item_id="+c.id+"]").addClass("success");this._signRandID(a);jQuery("#"+a.id).hasClass("popover-loaded")||
jQuery("#"+a.id).popover({title:'<div class="row"><div class="col-xs-10">Details for: '+c.name+'</div><div class="col-xs-2" style="cursor: pointer" href="javascript:void(0);" onclick="jQuery(\'#'+a.id+"').popover('hide');\"><span class=\"pull-right glyphicon glyphicon-remove\" ></span></div></div>",html:!0,placement:function(){return b?"left":"right"},container:"body",trigger:"manual",viewport:{selector:".list-panel",padding:0},content:function(){return b?"<p>"+c.address.shipping.full+"</p>":"<p>"+
c.address.billing.full+"</p>"},template:'<div class="popover" role="tooltip" style="max-width: none; z-index: 0;"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'}).addClass("popover-loaded");jQuery("#"+a.id).popover("toggle");return this},_getResultRow:function(a,c){var b={me:this};b.tag=!0===b.isTitle?"th":"td";b.isTitle=c||!1;b.row=(new Element("tr",{"class":(!0===b.isTitle?"item_top_row":"btn-hide-row item_row")+(0==a.active?" danger":""),item_id:!0===
b.isTitle?"":a.id})).store("data",a).insert({bottom:(new Element(b.tag,{"class":"col-xs-1"})).update(a.raNo).setStyle("cursor: pointer;").observe("click",function(){b.me._openEditPage(a)})}).insert({bottom:(new Element(b.tag,{"class":"col-xs-1"})).update(a.description)}).insert({bottom:(new Element(b.tag,{"class":"col-xs-1"})).update(b.isTitle?b.me._getTitleRowData().totalValue:b.me.getCurrency(a.totalValue))}).insert({bottom:(new Element(b.tag,{"class":"col-xs-1"})).update(a.status)}).insert({bottom:(new Element(b.tag,
{"class":"col-xs-1"})).update(a.customer.name)}).insert({bottom:(new Element(b.tag,{"class":"col-xs-1"})).update(a.order.orderNo?a.order.orderNo:"")}).insert({bottom:(new Element(b.tag,{"class":"col-xs-1"})).update(b.isTitle?"No of RMA NoteItems":a.raItems?a.raItems.length:"")}).insert({bottom:(new Element(b.tag,{"class":"col-xs-1"})).setStyle("display: none;").insert({bottom:!0===b.isTitle?a.active:new Element("input",{type:"checkbox",disabled:!0,checked:a.active})})}).insert({bottom:(new Element(b.tag,
{"class":"text-right col-xs-1"})).update(!0===b.isTitle?"":(new Element("span",{"class":"btn-group btn-group-xs"})).insert({bottom:(new Element("span",{"class":"btn btn-default",title:"Edit"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-pencil"})}).observe("click",function(){$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")});b.me._openEditPage(a)})}).insert({bottom:(new Element("span",{"class":"btn btn-danger",title:"Delete"})).insert({bottom:new Element("span",
{"class":"glyphicon glyphicon-trash"})}).observe("click",function(){if(!confirm("Are you sure you want to deactivate this item?"))return!1;a.active&&b.me._deactivateItem(this);$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")})})})).observe("click",function(){b.me._highlightSelectedRow(this);$$(".popover-loaded").each(function(a){jQuery(a).popover("hide")})})});return b.row},_getNextPageBtn:function(){var a;a=this;return(new Element("tfoot")).insert({bottom:(new Element("tr")).insert({bottom:(new Element("td",
{colspan:"8","class":"text-center"})).insert({bottom:(new Element("span",{"class":"btn btn-primary","data-loading-text":"Fetching more results ..."})).update("Show More").observe("click",function(){a._pagination.pageNo=1*a._pagination.pageNo+1;jQuery(this).button("loading");a.getResults()})})})})},_deactivateItem:function(a){var c,b,d;c=this;b=$(a).up("[item_id]");a=b.retrieve("data");c.postAjax(c.getCallbackId("deactivateItems"),{item_id:a.id},{onCreate:function(){b&&(b.toggleClassName("danger"),
b.hide())},onSuccess:function(a,e){try{b.toggleClassName("danger");d=c.getResp(e,!1,!0);if(!d.item)throw"errror";$$('[item_id="'+d.item.id+'"]').first().replace(c._getResultRow(d.item,!1));c._highlightSelectedRow($$('[item_id="'+d.item.id+'"]').first().down(".glyphicon.glyphicon-trash"))}catch(f){c.showModalBox('<span class="text-danger">ERROR</span>',f,!0)}}})}});