var PageJs=new Class.create;
PageJs.prototype=Object.extend(new BPCPageJs,{_resultDivId:"",_addCompanyDivId:"",_pageInfo:{pageNo:1,pageSize:30},_searchCriteria:"",_getEditAliasRow:function(a){var b,c,d,e,g,h,f;b=this;return(new Element("div",{"class":"input-group input-group-sm pmc_row"})).insert({bottom:(new Element("span",{"class":"input-group-btn",title:"Save"})).insert({bottom:(new Element("span",{id:"save_btn_"+a.id,"class":"btn btn-success","data-loading-text":"saving..."})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-floppy-saved"})})}).observe("click",
function(){c=this;d=$(c).up(".pmc_row");e=$F(d.down(".aliasValue"));e.blank()?(d.addClassName("has-error"),d.insert({after:b.getAlertBox("Error:","Alias is required").addClassName("alert-danger")})):(g={id:a.id||"",newAliasValue:e,companyName:a.companyName||$F(d.up(".company_row").down(".company_name"))},b.postAjax(b.getCallbackId("updatePriceMatchCompany"),g,{onCreate:function(a,b){jQuery(c.id).button("loading")},onSuccess:function(a,c){try{h=b.getResp(c,!1,!0),(f=d.up(".company_row").down(".company_name"))&&
!f.hasClassName("noborder")&&f.writeAttribute("readOnly",!0).addClassName("noborder"),d.replace(b._getAliasRow(h.item))}catch(e){d.insert({after:b.getAlertBox("Error:",e).addClassName("alert-danger")})}},onComplete:function(a,b){jQuery(c.id).button("reset")}}))})}).insert({bottom:new Element("input",{type:"text","class":"form-control aliasValue",value:a.companyAlias||""})}).insert({bottom:(new Element("span",{"class":"input-group-btn",title:"Cancel"})).insert({bottom:(new Element("span",{"class":"btn btn-warning"})).insert({bottom:new Element("span",
{"class":"glyphicon glyphicon-floppy-remove"})})}).observe("click",function(){a.id?$(this).up(".pmc_row").replace(b._getAliasRow(a)):$(this).up(".pmc_row").remove()})})},_getAliasRow:function(a){var b,c,d,e,g,h,f,k;b=this;if((c=a.companyAlias)&&""!==c&&null!==c&&void 0!==c)return(new Element("div",{"class":"input-group input-group-sm pmc_row"})).store("data",a).insert({bottom:(new Element("span",{"class":"input-group-btn",title:"Edit"})).insert({bottom:(new Element("span",{"class":"btn btn-default"})).update(new Element("span",
{"class":"glyphicon glyphicon-pencil"}))}).observe("click",function(){d=this;e=$(d).up(".pmc_row");g=b._getEditAliasRow(e.retrieve("data"));e.replace(g);g.down(".aliasValue").select()})}).insert({bottom:(new Element("div",{"class":"form-control"})).update(c)}).insert({bottom:(new Element("span",{"class":"input-group-btn",title:"Delete"})).insert({bottom:(new Element("span",{"class":"btn btn-danger"})).update(new Element("span",{"class":"glyphicon glyphicon-trash"}))}).observe("click",function(){h=
confirm("Are you sure you want to delete this alias ?");!1!==h&&(f=$(this).up(".pmc_row"),b.postAjax(b.getCallbackId("deleteAliasForPriceMatchCompany"),{data:a},{onCreate:function(a,b){},onSuccess:function(a,c){try{b.getResp(c,!1,!0),k=f.up(".company_row"),f.remove(),0===k.getElementsBySelector(".pmc_row").size()&&k.remove()}catch(d){alert(d)}}}))})})},_getCompanyRow:function(a){var b,c,d;b=this;c=new Element("div",{"class":"col-xs-8 company_alias"});a.companyAliases.each(function(a){c.insert({bottom:b._getAliasRow(a)})});
c.insert({bottom:(new Element("botton",{"class":"btn btn-success btn-xs"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-plus-sign"})}).observe("click",function(){$(this).insert({before:b._getEditAliasRow({})})})});d=new Element("input",{"class":"company_name",type:"text",value:a.companyName});a.companyName.blank()||d.writeAttribute("readOnly",!0).addClassName("noborder");return(new Element("div",{"class":"row list-group-item company_row"})).store("allCompanyAliasData",a).insert({bottom:(new Element("div",
{"class":"col-xs-4"})).update(d)}).insert({bottom:c})},displayAllPriceMatchCompany:function(){var a,b;a=this;a.postAjax(a.getCallbackId("getPriceMatchCompany"),{searchCriteria:a._searchCriteria,pagination:a._pageInfo},{onCreate:function(a,b){},onSuccess:function(c,d){try{b=a.getResp(d,!1,!0),b.items.each(function(b){$(a._resultDivId).insert({bottom:a._getCompanyRow(b)})})}catch(e){alert(e)}}});return a},newCompany:function(){$(this._resultDivId).insert({bottom:this._getCompanyRow({companyName:"",
companyAliases:[]})});return this}});