var PageJs=new Class.create;
PageJs.prototype=Object.extend(new DetailsPageJs,{_customer:{},setPreData:function(b){this._customer=b;return this},_getItemDiv:function(){var b;b=this;return(new Element("div",{"class":"customer-editing-container"})).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:b._getCustomerSummaryDiv(b._item).wrap(new Element("div",{"class":"col-sm-12"}))})}).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:b._getCustomerBillingSummaryDiv(b._item).wrap(new Element("div",{"class":"col-sm-6"}))}).insert({bottom:b._getCustomerShippingSummaryDiv(b._item).wrap(new Element("div",
{"class":"col-sm-6"}))})}).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("span",{id:"saveBtn","class":"btn btn-primary pull-right col-sm-4","data-loading-text":"saving ..."})).update("Save").observe("click",function(){b._submitSave(this)})})})},_submitSave:function(b){var a,c;a=this;c=a._collectFormData($(a.getHTMLID("itemDiv")),"save-item");c.id=a._customer.id?a._customer.id:"";if(null===c)return a;a.saveItem(b,c,function(b){a.showModalBox('<strong class="text-success">Saved Successfully!</strong>',
"Saved Successfully!",!0);a._item=b.item;a.refreshParentWindow();window.parent.jQuery.fancybox.close()});return a},_bindSaveKey:function(){var b;b=this;$$(".customer-editing-container").first().getElementsBySelector("[save-item]").each(function(a){a.observe("keydown",function(a){b.keydown(a,function(){$$(".customer-editing-container").first().down("#saveBtn").click()})})});return this},refreshParentWindow:function(){var b,a;window.parent&&(b=window.parent,(a=$(b.document.body).down("#"+b.pageJs.resultDivId+
" .item_row[item_id="+this._item.id+"]"))&&a.replace(b.pageJs._getResultRow(this._item).addClassName("success")))},_getCustomerSummaryDiv:function(b){return(new Element("div",{"class":"panel panel-default"})).insert({bottom:(new Element("div",{"class":"panel-heading"})).insert({bottom:(new Element("a",{href:"javascript: void(0);",title:"click to show/hide below"})).insert({bottom:(new Element("strong")).update(b.name?"Editing: "+b.name:"Creating new customer: ")})}).observe("click",function(){$(this).up(".panel").down(".panel-body").toggle()})}).insert({bottom:(new Element("div",
{"class":"panel-body"})).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-4"})).update(this._getFormGroup("Company Name / Customer Name",new Element("input",{required:!0,"save-item":"name",type:"text",value:b.name?b.name:""})))}).insert({bottom:(new Element("div",{"class":"col-sm-4"})).update(this._getFormGroup("Email",new Element("input",{"save-item":"email",type:"email",value:b.email?b.email:""})))}).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update(this._getFormGroup("Contact No?",
new Element("input",{"save-item":"contactNo",type:"value",value:b.contactNo?b.contactNo:""})))}).insert({bottom:(new Element("div",{"class":"col-sm-1"})).update(this._getFormGroup("Active?",new Element("input",{"save-item":"active",type:"checkbox",checked:b.active?b.active:!0})))})})})},_copyInfoFields:function(b,a,c,d){""!==$$(".customer-editing-container").first().down("#"+a+"-info #"+a+d+" input").value&&$(b).up(".panel").down("#"+c+d+" input").writeAttribute("value",$$(".customer-editing-container").first().down("#"+
a+"-info #"+a+d+" input").value)},_getCustomerBillingSummaryDiv:function(b){var a,c;a=this;c=b.id&&b.address&&b.address.billing?b.address.billing:{};return(new Element("div",{"class":"panel panel-default",id:"billing-info"})).insert({bottom:(new Element("div",{"class":"panel-heading"})).insert({bottom:(new Element("strong")).update(b.name?"Billing Info: "+b.name:"Billing Info: new customer")}).insert({bottom:(new Element("small",{"class":"pull-right"})).insert({bottom:(new Element("button",{"class":"btn btn-default btn-xs",
type:"button"})).update("Copy from Shipping")})}).observe("click",function(){a._copyInfoFields($(this),"shipping","billing","CompanyName");a._copyInfoFields($(this),"shipping","billing","Name");a._copyInfoFields($(this),"shipping","billing","ContactNo");a._copyInfoFields($(this),"shipping","billing","Street");a._copyInfoFields($(this),"shipping","billing","City");a._copyInfoFields($(this),"shipping","billing","State");a._copyInfoFields($(this),"shipping","billing","Country");a._copyInfoFields($(this),
"shipping","billing","Posecode")})}).insert({bottom:(new Element("div",{"class":"panel-body"})).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-12",id:"billingCompanyName"})).update(a._getFormGroup("Company Name",new Element("input",{"save-item":"billingCompanyName",type:"text",value:c.companyName?c.companyName:""})))})}).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-12",id:"billingName"})).update(a._getFormGroup("Name",
new Element("input",{"save-item":"billingName",type:"text",value:c.contactName?c.contactName:""})))})}).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-12",id:"billingContactNo"})).update(a._getFormGroup("Contact No.",new Element("input",{"save-item":"billingContactNo",type:"value",value:c.contactNo?c.contactNo:""})))})}).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-6",id:"billingStreet"})).update(a._getFormGroup("Street",
new Element("input",{"save-item":"billingStreet",type:"text",value:c.street?c.street:""})))}).insert({bottom:(new Element("div",{"class":"col-sm-6",id:"billingCity"})).update(a._getFormGroup("City",new Element("input",{"save-item":"billingCity",type:"text",value:c.city?c.city:""})))})}).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-4",id:"billingState"})).update(a._getFormGroup("State",new Element("input",{"save-item":"billingState",type:"text",
value:c.region?c.region:""})))}).insert({bottom:(new Element("div",{"class":"col-sm-4",id:"billingCountry"})).update(a._getFormGroup("Country",new Element("input",{"save-item":"billingCountry",type:"text",value:c.country?c.country:""})))}).insert({bottom:(new Element("div",{"class":"col-sm-4",id:"billingPosecode"})).update(a._getFormGroup("Post Code",new Element("input",{"save-item":"billingPosecode",type:"text",value:c.postCode?c.postCode:""})))})})})},_getCustomerShippingSummaryDiv:function(b){var a,
c;a=this;c=b.id&&b.address&&b.address.shipping?b.address.shipping:{};return(new Element("div",{"class":"panel panel-default",id:"shipping-info"})).insert({bottom:(new Element("div",{"class":"panel-heading"})).insert({bottom:(new Element("strong")).update(b.name?"Shipping Info: "+b.name:"Shipping Info: new customer")}).insert({bottom:(new Element("small",{"class":"pull-right"})).insert({bottom:(new Element("button",{"class":"btn btn-default btn-xs",type:"button"})).update("Copy from Billing")})}).observe("click",
function(){a._copyInfoFields($(this),"billing","shipping","CompanyName");a._copyInfoFields($(this),"billing","shipping","Name");a._copyInfoFields($(this),"billing","shipping","ContactNo");a._copyInfoFields($(this),"billing","shipping","Street");a._copyInfoFields($(this),"billing","shipping","City");a._copyInfoFields($(this),"billing","shipping","State");a._copyInfoFields($(this),"billing","shipping","Country");a._copyInfoFields($(this),"billing","shipping","Posecode")})}).insert({bottom:(new Element("div",
{"class":"panel-body"})).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-12",id:"shippingCompanyName"})).update(a._getFormGroup("Company Name",new Element("input",{"save-item":"shippingCompanyName",type:"text",value:c.companyName?c.companyName:""})))})}).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-12",id:"shippingName"})).update(a._getFormGroup("Name",new Element("input",{"save-item":"shippingName",
type:"text",value:c.contactName?c.contactName:""})))})}).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-12",id:"shippingContactNo"})).update(a._getFormGroup("Contact No.",new Element("input",{"save-item":"shippingContactNo",type:"value",value:c.contactNo?c.contactNo:""})))})}).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-6",id:"shippingStreet"})).update(a._getFormGroup("Street",new Element("input",
{"save-item":"shippingStreet",type:"text",value:c.street?c.street:""})))}).insert({bottom:(new Element("div",{"class":"col-sm-6",id:"shippingCity"})).update(a._getFormGroup("City",new Element("input",{"save-item":"shippingCity",type:"text",value:c.city?c.city:""})))})}).insert({bottom:(new Element("div",{"class":"row"})).insert({bottom:(new Element("div",{"class":"col-sm-4",id:"shippingState"})).update(a._getFormGroup("State",new Element("input",{"save-item":"shippingState",type:"text",value:c.region?
c.region:""})))}).insert({bottom:(new Element("div",{"class":"col-sm-4",id:"shippingCountry"})).update(a._getFormGroup("Country",new Element("input",{"save-item":"shippingCountry",type:"text",value:c.country?c.country:""})))}).insert({bottom:(new Element("div",{"class":"col-sm-4",id:"shippingPosecode"})).update(a._getFormGroup("Post Code",new Element("input",{"save-item":"shippingPosecode",type:"text",value:c.postCode?c.postCode:""})))})})})},_getFormGroup:function(b,a){return(new Element("div",{"class":"form-group form-group-sm form-group-sm-label"})).insert({bottom:(new Element("label")).update(b)}).insert({bottom:a.addClassName("form-control")})},
bindAllEventNObjects:function(){return this}});