var PaymentListPanelJs=new Class.create;
PaymentListPanelJs.prototype={_pageJs:null,_order:null,_creditNote:null,_canEdit:!1,_panelHTMLID:"",_showNotifyCustBox:!0,initialize:function(b,c,a,d,e){this._pageJs=b;this._panelHTMLID="PaymentListPanelJs_"+String.fromCharCode(65+Math.floor(26*Math.random()))+Date.now();this._order=c;this._creditNote=a;this._showNotifyCustBox=!1===e?!1:!0;this._canEdit=d||this._canEdit},setAfterAddFunc:function(b){this._afterAddFunc=b;return this},setAfterDeleteFunc:function(b){this._afterDeleteFunc=b;return this},
getPaymentListPanel:function(){return(new Element("div",{"class":"panel panel-default",id:this._panelHTMLID})).store("PaymentListPanelJs",this).insert({bottom:(new Element("div",{"class":"panel-heading"})).update("Payments: ")}).insert({bottom:(new Element("div",{"class":"panel-body"})).update(this._pageJs.getLoadingImg())})},_deletePayment:function(b,c){var a,d,e,f,g;a=this;d=$(b).up(".deletion-confirm");d.getElementsBySelector(".msg").each(function(a){a.remove()});e=a._pageJs._collectFormData(d,
"deletion-confirm");if(null!==e)return e.paymentId=c.id,a._pageJs.postAjax(PaymentListPanelJs.callbackIds.delPayment,e,{onCreate:function(){a._signRandID(b);jQuery("#"+b.id).button("loading")},onSuccess:function(c,e){try{(f=a._pageJs.getResp(e,!1,!0))&&f.item&&((g=$(a._panelHTMLID).down(".payment-item[payment-id="+f.item.id+"]"))&&g.remove(),d.update('<h4 class="text-success">Payment delete successfully.</h4>'),d.up(".modal-content").down(".modal-header").update('<strong class="text-success">Success</strong>'),
"function"===typeof a._afterDeleteFunc&&a._afterDeleteFunc(f.item))}catch(k){$(b).insert({before:a._pageJs.getAlertBox("Error",k).addClassName("alert-danger").addClassName("msg")})}},onComplete:function(){jQuery("#"+b.id).button("reset")}}),a},_showComments:function(b){var c,a,d;c=this;a=$(b);c._pageJs._signRandID(b);a.hasClassName("popover-loaded")||jQuery.ajax({type:"GET",dataType:"json",url:"/ajax/getComments",data:{entity:a.readAttribute("comments-entity"),entityId:a.readAttribute("comments-entity-Id"),
type:""},success:function(e){d="N/A";e.resultData&&e.resultData.items&&0<e.resultData.items.length&&(d='<div class="list-group">',jQuery.each(e.resultData.items,function(a,b){d+='<div class="list-group-item">';d+='<span class="badge">'+b.type+"</span>";d+='<strong class="list-group-item-heading"><small>'+b.createdBy.person.fullname+"</small></strong>: ";d+="<p><small><em> @ "+c._pageJs.loadUTCTime(b.created).toLocaleString()+"</em></small><br /><small>"+b.comments+"</small></p>";d+="</div>"}),d+=
"</div>");jQuery("#"+b.id).popover({html:!0,placement:"left",title:'<div class="row" style="min-width: 200px;"><div class="col-xs-10">Comments:</div><div class="col-xs-2"><a class="pull-right" href="javascript:void(0);" onclick="jQuery(\'#'+a.readAttribute("id")+"').popover('hide');\"><strong>&times;</strong></a></div></div>",content:d}).popover("show");a.addClassName("popover-loaded")}});return c},_getPaymentRow:function(b,c){var a,d,e,f,g;a=this;d=!0===c?!0:!1;e=!0===d?"th":"td";d=(new Element("tr",
{"class":!0==="item "+d?"":"payment-item"})).store("data",b).insert({bottom:(new Element(e)).update(!0===d?"Date":moment(a._pageJs.loadUTCTime(b.paymentDate)).format("DD/MMM/YY"))}).insert({bottom:(new Element(e)).update(!0===d?"Method":b.method.name)}).insert({bottom:(new Element(e)).update(!0===d?"Value":a._pageJs.getCurrency(b.value))}).insert({bottom:(new Element(e)).update(!0===d?"Created":b.createdBy.person.fullname+" @ "+moment(a._pageJs.loadUTCTime(b.created)).format("DD/MM/YY h:mm a"))}).insert({bottom:(new Element(e)).update(!0===
d?"Comments":(new Element("a",{href:"javascript: void(0);","class":"text-muted visible-lg visible-md visible-sm visible-xs",title:"comments","comments-entity-id":b.id,"comments-entity":"Payment"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-comment"})}).observe("click",function(){a._showComments(this)}))}).insert({bottom:(new Element(e)).update(!0===d?"":!0!==a._canEdit?"":(new Element("a",{href:"javascript: void(0);","class":"text-danger",title:"Delete this payment"})).insert({bottom:new Element("span",
{"class":"glyphicon glyphicon-remove"})}).observe("click",function(){f=(new Element("div",{"class":"deletion-confirm"})).insert({bottom:(new Element("h4")).update("You are about to delete a payment with a value: "+a._pageJs.getCurrency(b.value)+" from Method: "+b.method.name)}).insert({bottom:(new Element("div",{"class":"form-group"})).insert({bottom:(new Element("label")).update('If you want to continue, please provide a reason/comments below and click <strong class="text-danger">"YES, Delete It"</strong> below:')}).insert({bottom:g=
new Element("input",{"class":"form-control",placeholder:"The reason of deleting this payment","deletion-confirm":"reason",required:!0})})}).insert({bottom:(new Element("span",{"class":"btn btn-danger","data-loading-text":'<i class="fa fa-refresh fa-spin"></i>'})).update("YES, Delete It").observe("click",function(){a._deletePayment(this,b)})}).insert({bottom:(new Element("span",{"class":"btn btn-default pull-right"})).update("NO, Cancel Deletion").observe("click",function(){a._pageJs.hideModalBox()})});
a._pageJs.showModalBox("Deleting a Payment?",f);$(g).focus()}))});b.id&&d.writeAttribute("payment-id",b.id);return d},_getFormGroup:function(b,c){return(new Element("div",{"class":"form-group"})).insert({bottom:b}).insert({bottom:c})},clearNewPaymentRow:function(){$(this._panelHTMLID).down(".new-payment-row").replace(this._getCreatePaymentRow());return this},_submitPayment:function(b){var c,a,d,e,f;c=this;a=$(b).up(".new-payment-div");a.getElementsBySelector(".msg").each(function(a){a.remove()});
d=c._pageJs._collectFormData(a,"payment_field");if(null===d)return c;if(e=a.down('[payment_field="paymentDate"]'))c._pageJs._signRandID(e),d.paymentDate=jQuery("#"+e.id).data("DateTimePicker").date().utc().format();e=null;c._order&&c._order.id?e={entity:"Order",entityId:c._order.id}:c._creditNote&&c._creditNote.id&&(e={entity:"CreditNote",entityId:c._creditNote.id});null!==e&&c._pageJs.postAjax(PaymentListPanelJs.callbackIds.addPayment,{payment:d,againstEntity:e},{onCreate:function(a,d){c._pageJs._signRandID(b);
jQuery("#"+b.id).button("loading")},onSuccess:function(b,d){try{(f=c._pageJs.getResp(d,!1,!0))&&f.item&&(a.insert({top:c._pageJs.getAlertBox("Success: ","Payment saved successfully!").addClassName("alert-success").addClassName("msg")}),$(c._panelHTMLID).down(".payment-list").insert({top:c._getPaymentRow(f.item)}),c.clearNewPaymentRow(),"function"===typeof c._afterAddFunc&&c._afterAddFunc(f.item))}catch(e){a.insert({top:c._pageJs.getAlertBox("",e).addClassName("alert-danger").addClassName("msg")})}},
onComplete:function(a,d){jQuery("#"+b.id).button("reset")}});return c},_currencyInputChanged:function(b){var c;if($F(b).blank())return!1;c=this._pageJs.getValueFromCurrency($F(b));if(null===c.match(/^(-)?\d+(\.\d{1,4})?$/))return this._pageJs._markFormGroupError(b,"Invalid currency format provided!"),!1;$(b).value=this._pageJs.getCurrency(c);return!0},_clearCreatePaymentRow:function(b,c){var a,d,e;a=this;d=b.up(".new-payment-div");d.getElementsBySelector(".after_select_method").each(function(a){a.remove()});
if($F(c).blank()||!0!==a._currencyInputChanged(c))$(c).select();else return d.insert({bottom:!0!==a._showNotifyCustBox?"":(new Element("div",{"class":"after_select_method  col-sm-3",title:"Notify Customer?"})).insert({bottom:a._getFormGroup((new Element("label",{"class":"control-label"})).update("Notify Cust.?"),(new Element("div",{"class":"text-center"})).update(new Element("input",{type:"checkbox","class":"input-sm",payment_field:"notifyCust",checked:!0})))})}).insert({bottom:(new Element("div",
{"class":"after_select_method control-label col-sm-6"})).insert({bottom:a._getFormGroup((new Element("label",{"class":"control-label"})).update("Comments:"),e=(new Element("input",{type:"text","class":"after_select_method input-sm form-control",payment_field:"extraComments",required:!0,placeholder:"Some Comments"})).observe("keydown",function(b){a._pageJs.keydown(b,function(){d.down(".add-btn").click()})}))})}).insert({bottom:(new Element("div",{"class":"after_select_method control-label col-sm-3"})).insert({bottom:a._getFormGroup("&nbsp;",
(new Element("span",{"class":"btn btn-primary form-control add-btn","data-loading-text":'<i class="fa fa-refresh fa-spin"></i>'})).update("Save").observe("click",function(){a._submitPayment(this)}))})}),e.select(),a},_getCreatePaymentRow:function(){var b,c,a;b=this;if(!0!==b._canEdit)return null;c=(new Element("tr",{"class":"new-payment-row"})).insert({bottom:(new Element("td",{colspan:4})).insert({bottom:(new Element("div",{"class":"new-payment-div"})).insert({bottom:(new Element("div",{"class":"col-sm-3"})).update(b._getFormGroup((new Element("label",
{"class":"control-label"})).update("Date: "),new Element("input",{"class":"input-sm form-control",payment_field:"paymentDate",required:!0})))}).insert({bottom:(new Element("div",{"class":"col-sm-5"})).update(b._getFormGroup((new Element("label",{"class":"control-label"})).update("Method: "),a=(new Element("select",{"class":"input-sm form-control",payment_field:"payment_method_id",required:!0})).insert({bottom:(new Element("option",{value:""})).update("Payment Method:")}).observe("change",function(){b._clearCreatePaymentRow(this,
c.down("[payment_field=paidAmount]"))})))}).insert({bottom:(new Element("div",{"class":"col-sm-4"})).update(b._getFormGroup((new Element("label",{"class":"control-label"})).update("Amt.: "),(new Element("input",{type:"text",payment_field:"paidAmount","class":"input-sm form-control",required:!0,validate_currency:!0,placeholder:"The paid amount"})).observe("change",function(){b._clearCreatePaymentRow(c.down("[payment_field=payment_method_id]"),this)})))})})});b.paymentMethods.each(function(b){a.insert({bottom:(new Element("option",
{value:b.id})).update(b.name)})});return c},_showPayments:function(b,c){var a,d,e,f,g,h,l,k,n,m;a=this;d=b||1;c&&a._pageJs._signRandID(c);e=null;a._order&&a._order.id?e={entity:"Order",entityId:a._order.id}:a._creditNote&&a._creditNote.id&&(e={entity:"CreditNote",entityId:a._creditNote.id});null!==e&&(e.pagination={pageNo:d},f=a._pageJs.getLoadingImg(),a._pageJs.postAjax(PaymentListPanelJs.callbackIds.getPayments,e,{onCreate:function(){1===d&&((g=$(a._panelHTMLID).down(".panel-body"))?g.update(f):
$(a._panelHTMLID).insert({bottom:(new ELement("div",{"class":"panel-body"})).update(f)}));c&&jQuery("#"+c.id).button("loading")},onSuccess:function(b,e){try{(h=a._pageJs.getResp(e,!1,!0))&&h.items&&((g=$(a._panelHTMLID).down(".panel-body"))&&g.remove(),l=$(a._panelHTMLID).down("thead"),(k=$(a._panelHTMLID).down(".payment-list"))&&l||$(a._panelHTMLID).insert({bottom:(new Element("table",{"class":"table table-hover table-condensed"})).insert({bottom:l=(new Element("thead")).update(a._getPaymentRow({},
!0))}).insert({bottom:k=new Element("tbody",{"class":"payment-list"})})}),1===d&&h.paymentMethods&&(a.paymentMethods=h.paymentMethods,l.insert({top:n=a._getCreatePaymentRow()}),n&&(m=n.down('[payment_field="paymentDate"]')))&&(a._pageJs._signRandID(m),jQuery("#"+m.id).datetimepicker({format:"DD/MM/YYYY"}),jQuery("#"+m.id).data("DateTimePicker").date(new Date)),h.items.each(function(b){k.insert({bottom:a._getPaymentRow(b)})}),h.pagination&&h.pagination.pageNumber<h.pagination.totalPages&&k.insert({bottom:(new Element("tr",
{"class":"get-more-btn-wrapper"})).update((new Element("td",{colspan:4})).update((new Element("div",{"class":"btn btn-primary"})).update("Show More Payments").observe("click",function(){a._showPayments(1*d+1,c)})))}))}catch(f){(g=$(a._panelHTMLID).down(".panel-body"))?g.update(a._pageJs.getAlertBox("Error: ",f).addClassName("alert-danger")):a._pageJs.showModalBox('<strong class="text-danger">Error</strong>',f)}},onComplete:function(){f.remove();c&&jQuery("#"+c.id).button("reset")}}))},load:function(){$(this._panelHTMLID)&&
this._showPayments();return this}};